// AUTO-GENERATED by backend/pipelines/build_frontend_data.py
// DO NOT EDIT MANUALLY — regenerate via: python3 pipelines/build_frontend_data.py
// 데이터 소스: backend/data/historical/* + backend/data/forecast/forecast_v2_*.json
//             + backend/data/news/latest.json + backend/data/events/latest.json
// 생성 시각: 2026-09-20T17:33:26.404008Z
// 뉴스/이벤트: news 10건 (키워드 휴리스틱, 2026-09-20) · events 9건 (기상이변 제외)
// UI 컴포넌트는 design_handoff_sixsense_dram_dashboard 의 SIXSENSE_DATA 스키마를 그대로 따른다.

export const SIXSENSE_DATA = {
  "meta": {
    "current": 7.154,
    "currentChange": "+3.2%",
    "pred7": 7.534,
    "pred7Change": "+5.3%",
    "pred21": 7.806,
    "pred21Change": "+9.1%",
    "updated": "2026-09-20 06:00 KST",
    "model": "GBR (단기) + LSTM (중장기) + Prophet (베이스)",
    "confidence": 81,
    "insight": {
      "headline": "상승·상승 동조, 상승 시그널",
      "summary": "단기 **GBR** 모델은 7주 후 **$7.53** (**+5.3%**)를, 중장기 **LSTM** 모델은 21주 후 **$7.81** (**+9.2%**)를 가리킵니다. A-4 재고지수 4.92(<95)로 공급 타이트 신호.DXY 101.0로 강달러 압력↑.최근 30일 핵심 뉴스 5건이 동반. 종합적으로 향후 **AI 서버 수요** 증가세와 **HBM 캡 증설** 속도, **지정학 리스크** 변화를 주간 단위로 모니터링하며 호라이즌별로 차별화된 대응이 필요합니다.",
      "tone": "pos",
      "confidence": 55,
      "horizon": "mid",
      "keySignals": [
        "A-2",
        "B-4"
      ],
      "model": "휴리스틱 (LLM 모두 실패)",
      "generatedAt": "2026-09-20T17:33:26"
    },
    "modelValidation": {
      "headline": "단기 예측 검증 — 우수 모델 LIGHTGBM MAPE 7.53% (Prophet 기준선 35.96%, rolling-origin N=28)",
      "shortRows": [
        {
          "model": "Prophet",
          "mape": 35.96,
          "eval": "baseline",
          "winner": false
        },
        {
          "model": "xgboost",
          "mape": 8.18,
          "eval": "중간",
          "winner": false
        },
        {
          "model": "lightgbm",
          "mape": 7.53,
          "eval": "79.1% 개선",
          "winner": true
        },
        {
          "model": "단순 기준선 (마지막 값 유지)",
          "mape": 6.64,
          "eval": "기준선",
          "winner": false
        }
      ],
      "midRows": [
        {
          "model": "LSTM (PyTorch 2-layer hidden=64)",
          "mape": 49.46
        },
        {
          "model": "단순 기준선 (마지막 값 유지)",
          "mape": 27.02
        }
      ],
      "midCaution": "중장기 LSTM 오차(49.46%)가 단순 기준선(27.02%)보다 큽니다. 8~21주 예측은 방향성 참고용으로만 보세요.",
      "trainTimes": [
        {
          "name": "Prophet",
          "sec": 0.92
        },
        {
          "name": "Tree (단기)",
          "sec": 3.75
        },
        {
          "name": "LSTM (중장기)",
          "sec": 5.46
        }
      ],
      "trainTotal": 10.1,
      "architecture": "20개 신호 통합 DataFrame (108주 × 20열, sentiment 3주 MA)\n            │\n   ┌────────┼────────┐\n   ▼        ▼        ▼\n[Prophet] [Tree]  [LSTM]\nbaseline  단기      중장기\n         ─우수─    PyTorch\n         자동선정   2-layer",
      "envNote": "단기 트리 엔진: xgboost + lightgbm (실행 환경에 따라 자동 선택 — XGBoost/LightGBM 우선, libomp 미설치 시 sklearn GBR/HistGBR). LSTM은 PyTorch. MAPE는 학습에 사용하지 않은 held-out 구간에서 측정한 값입니다."
    }
  },
  "history": [
    {
      "week": -51,
      "value": 1.309,
      "type": "actual"
    },
    {
      "week": -50,
      "value": 1.523,
      "type": "actual"
    },
    {
      "week": -49,
      "value": 1.552,
      "type": "actual"
    },
    {
      "week": -48,
      "value": 1.691,
      "type": "actual"
    },
    {
      "week": -47,
      "value": 1.813,
      "type": "actual"
    },
    {
      "week": -46,
      "value": 1.919,
      "type": "actual"
    },
    {
      "week": -45,
      "value": 1.969,
      "type": "actual"
    },
    {
      "week": -44,
      "value": 1.979,
      "type": "actual"
    },
    {
      "week": -43,
      "value": 1.766,
      "type": "actual"
    },
    {
      "week": -42,
      "value": 1.913,
      "type": "actual"
    },
    {
      "week": -41,
      "value": 1.959,
      "type": "actual"
    },
    {
      "week": -40,
      "value": 2.008,
      "type": "actual"
    },
    {
      "week": -39,
      "value": 2.072,
      "type": "actual"
    },
    {
      "week": -38,
      "value": 2.245,
      "type": "actual"
    },
    {
      "week": -37,
      "value": 2.498,
      "type": "actual"
    },
    {
      "week": -36,
      "value": 2.732,
      "type": "actual"
    },
    {
      "week": -35,
      "value": 2.85,
      "type": "actual"
    },
    {
      "week": -34,
      "value": 3.023,
      "type": "actual"
    },
    {
      "week": -33,
      "value": 3.279,
      "type": "actual"
    },
    {
      "week": -32,
      "value": 3.109,
      "type": "actual"
    },
    {
      "week": -31,
      "value": 3.302,
      "type": "actual"
    },
    {
      "week": -30,
      "value": 3.479,
      "type": "actual"
    },
    {
      "week": -29,
      "value": 3.634,
      "type": "actual"
    },
    {
      "week": -28,
      "value": 3.209,
      "type": "actual"
    },
    {
      "week": -27,
      "value": 3.403,
      "type": "actual"
    },
    {
      "week": -26,
      "value": 3.556,
      "type": "actual"
    },
    {
      "week": -25,
      "value": 3.14,
      "type": "actual"
    },
    {
      "week": -24,
      "value": 3.13,
      "type": "actual"
    },
    {
      "week": -23,
      "value": 3.593,
      "type": "actual"
    },
    {
      "week": -22,
      "value": 3.884,
      "type": "actual"
    },
    {
      "week": -21,
      "value": 4.174,
      "type": "actual"
    },
    {
      "week": -20,
      "value": 4.436,
      "type": "actual"
    },
    {
      "week": -19,
      "value": 5.892,
      "type": "actual"
    },
    {
      "week": -18,
      "value": 5.964,
      "type": "actual"
    },
    {
      "week": -17,
      "value": 6.287,
      "type": "actual"
    },
    {
      "week": -16,
      "value": 7.717,
      "type": "actual"
    },
    {
      "week": -15,
      "value": 7.017,
      "type": "actual"
    },
    {
      "week": -14,
      "value": 7.565,
      "type": "actual"
    },
    {
      "week": -13,
      "value": 9.004,
      "type": "actual"
    },
    {
      "week": -12,
      "value": 8.842,
      "type": "actual"
    },
    {
      "week": -11,
      "value": 7.818,
      "type": "actual"
    },
    {
      "week": -10,
      "value": 7.464,
      "type": "actual"
    },
    {
      "week": -9,
      "value": 6.442,
      "type": "actual"
    },
    {
      "week": -8,
      "value": 6.617,
      "type": "actual"
    },
    {
      "week": -7,
      "value": 6.217,
      "type": "actual"
    },
    {
      "week": -6,
      "value": 5.986,
      "type": "actual"
    },
    {
      "week": -5,
      "value": 6.774,
      "type": "actual"
    },
    {
      "week": -4,
      "value": 6.877,
      "type": "actual"
    },
    {
      "week": -3,
      "value": 6.567,
      "type": "actual"
    },
    {
      "week": -2,
      "value": 6.894,
      "type": "actual"
    },
    {
      "week": -1,
      "value": 6.933,
      "type": "actual"
    },
    {
      "week": 0,
      "value": 7.154,
      "type": "actual"
    }
  ],
  "forecast7": [
    {
      "week": 1,
      "value": 7.154,
      "lower": 6.615,
      "upper": 7.693,
      "type": "f7"
    },
    {
      "week": 2,
      "value": 7.424,
      "lower": 6.865,
      "upper": 7.983,
      "type": "f7"
    },
    {
      "week": 3,
      "value": 7.543,
      "lower": 6.975,
      "upper": 8.111,
      "type": "f7"
    },
    {
      "week": 4,
      "value": 6.509,
      "lower": 6.019,
      "upper": 6.999,
      "type": "f7"
    },
    {
      "week": 5,
      "value": 5.704,
      "lower": 5.274,
      "upper": 6.134,
      "type": "f7"
    },
    {
      "week": 6,
      "value": 6.751,
      "lower": 6.243,
      "upper": 7.259,
      "type": "f7"
    },
    {
      "week": 7,
      "value": 7.534,
      "lower": 6.967,
      "upper": 8.101,
      "type": "f7"
    }
  ],
  "forecast21": [
    {
      "week": 8,
      "value": 7.534,
      "lower": 3.808,
      "upper": 11.26,
      "type": "f21"
    },
    {
      "week": 9,
      "value": 7.708,
      "lower": 3.896,
      "upper": 11.52,
      "type": "f21"
    },
    {
      "week": 10,
      "value": 7.424,
      "lower": 3.752,
      "upper": 11.096,
      "type": "f21"
    },
    {
      "week": 11,
      "value": 7.35,
      "lower": 3.715,
      "upper": 10.985,
      "type": "f21"
    },
    {
      "week": 12,
      "value": 7.57,
      "lower": 3.826,
      "upper": 11.314,
      "type": "f21"
    },
    {
      "week": 13,
      "value": 7.767,
      "lower": 3.925,
      "upper": 11.609,
      "type": "f21"
    },
    {
      "week": 14,
      "value": 7.827,
      "lower": 3.956,
      "upper": 11.698,
      "type": "f21"
    },
    {
      "week": 15,
      "value": 8.022,
      "lower": 4.054,
      "upper": 11.99,
      "type": "f21"
    },
    {
      "week": 16,
      "value": 8.207,
      "lower": 4.148,
      "upper": 12.266,
      "type": "f21"
    },
    {
      "week": 17,
      "value": 7.756,
      "lower": 3.92,
      "upper": 11.592,
      "type": "f21"
    },
    {
      "week": 18,
      "value": 7.486,
      "lower": 3.783,
      "upper": 11.189,
      "type": "f21"
    },
    {
      "week": 19,
      "value": 7.577,
      "lower": 3.829,
      "upper": 11.325,
      "type": "f21"
    },
    {
      "week": 20,
      "value": 7.583,
      "lower": 3.832,
      "upper": 11.334,
      "type": "f21"
    },
    {
      "week": 21,
      "value": 7.806,
      "lower": 3.945,
      "upper": 11.667,
      "type": "f21"
    }
  ],
  "forecast_prophet": [
    {
      "week": 1,
      "value": 7.154,
      "type": "prophet"
    },
    {
      "week": 2,
      "value": 7.352,
      "type": "prophet"
    },
    {
      "week": 3,
      "value": 7.549,
      "type": "prophet"
    },
    {
      "week": 4,
      "value": 7.747,
      "type": "prophet"
    },
    {
      "week": 5,
      "value": 7.945,
      "type": "prophet"
    },
    {
      "week": 6,
      "value": 8.142,
      "type": "prophet"
    },
    {
      "week": 7,
      "value": 8.34,
      "type": "prophet"
    },
    {
      "week": 8,
      "value": 8.538,
      "type": "prophet"
    },
    {
      "week": 9,
      "value": 8.735,
      "type": "prophet"
    },
    {
      "week": 10,
      "value": 8.933,
      "type": "prophet"
    },
    {
      "week": 11,
      "value": 9.131,
      "type": "prophet"
    },
    {
      "week": 12,
      "value": 9.328,
      "type": "prophet"
    },
    {
      "week": 13,
      "value": 9.526,
      "type": "prophet"
    },
    {
      "week": 14,
      "value": 9.724,
      "type": "prophet"
    },
    {
      "week": 15,
      "value": 9.921,
      "type": "prophet"
    },
    {
      "week": 16,
      "value": 10.119,
      "type": "prophet"
    },
    {
      "week": 17,
      "value": 10.317,
      "type": "prophet"
    },
    {
      "week": 18,
      "value": 10.514,
      "type": "prophet"
    },
    {
      "week": 19,
      "value": 10.712,
      "type": "prophet"
    },
    {
      "week": 20,
      "value": 10.91,
      "type": "prophet"
    },
    {
      "week": 21,
      "value": 11.107,
      "type": "prophet"
    }
  ],
  "forecast_histgbr": [
    {
      "week": 1,
      "value": 7.154,
      "type": "histgbr"
    },
    {
      "week": 2,
      "value": 7.248,
      "type": "histgbr"
    },
    {
      "week": 3,
      "value": 8.106,
      "type": "histgbr"
    },
    {
      "week": 4,
      "value": 8.697,
      "type": "histgbr"
    },
    {
      "week": 5,
      "value": 8.742,
      "type": "histgbr"
    },
    {
      "week": 6,
      "value": 8.592,
      "type": "histgbr"
    },
    {
      "week": 7,
      "value": 8.336,
      "type": "histgbr"
    }
  ],
  "signalsA": [
    {
      "id": "A-1",
      "name": "대만 공급망",
      "source": "Yahoo Finance: TSM",
      "value": "+2.6%",
      "num": 0.0262,
      "tone": "neu",
      "desc": "TSMC·UMC 주가 (Yahoo Finance 블렌드)",
      "spark": [
        0.0,
        0.26,
        0.188,
        0.347,
        1.0,
        0.515,
        0.538,
        0.536
      ]
    },
    {
      "id": "A-3",
      "name": "관세청 수출",
      "source": "관세청 data.go.kr Itemtrade HS 854232",
      "value": "9248.05M",
      "num": 9248046034.0,
      "tone": "neu",
      "desc": "메모리 반도체 수출액 (관세청 Open API)",
      "spark": [
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5
      ]
    },
    {
      "id": "A-4",
      "name": "재고/출하 지수",
      "source": "KOSIS 광공업동향 C26 재고지수",
      "value": "4.92M",
      "num": 4923610.0,
      "tone": "alert",
      "desc": "100 초과 = 공급과잉 (KOSIS Open API)",
      "spark": [
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5
      ]
    },
    {
      "id": "A-5",
      "name": "AWS Spot 가격",
      "source": "AWS EC2 m6i.xlarge spot",
      "value": "$0.13",
      "num": 0.133,
      "tone": "pos",
      "desc": "p4d.24xlarge 시간당 (AWS Pricing API)",
      "spark": [
        0.263,
        0.0,
        0.207,
        0.133,
        0.169,
        0.472,
        0.799,
        1.0
      ]
    },
    {
      "id": "A-6",
      "name": "Manifold 봉쇄확률",
      "source": "Manifold Markets 'Will China launch a fu",
      "value": "32%",
      "num": 0.3184,
      "tone": "neu",
      "desc": "대만 침공 확률 (Manifold Markets)",
      "spark": [
        1.0,
        0.819,
        0.851,
        0.822,
        0.562,
        0.0,
        0.072,
        0.755
      ]
    },
    {
      "id": "A-7",
      "name": "구리 선물가",
      "source": "Yahoo Finance HG=F",
      "value": "$6.28",
      "num": 6.282,
      "tone": "neu",
      "desc": "10주 선행 → DRAM (COMEX HG=F)",
      "spark": [
        0.694,
        0.754,
        0.422,
        1.0,
        0.735,
        0.0,
        0.104,
        0.486
      ]
    }
  ],
  "signalsB": [
    {
      "id": "B-1",
      "name": "Earnings Call",
      "source": "Google News 'Earnings Call sentiment'",
      "value": "+1.00",
      "num": 1.0,
      "tone": "pos",
      "desc": "메모리 4사 콜 감성 (Google News+LLM)",
      "spark": [
        0.5,
        0.667,
        0.5,
        0.667,
        1.0,
        1.0,
        0.0,
        1.0
      ]
    },
    {
      "id": "B-5",
      "name": "LTA 비율",
      "source": "Google News 'LTA ratio'",
      "value": "+1.00",
      "num": 1.0,
      "tone": "pos",
      "desc": "장기 계약가/현물가 (DRAMeXchange)",
      "spark": [
        0.0,
        0.0,
        0.0,
        0.0,
        1.0,
        0.0,
        0.0,
        1.0
      ]
    },
    {
      "id": "B-6",
      "name": "HBM/D램 믹스",
      "source": "Google News 'HBM mix'",
      "value": "+0.00",
      "num": 0.0,
      "tone": "neu",
      "desc": "HBM 비중 변화 (TrendForce)",
      "spark": [
        1.0,
        0.333,
        1.0,
        0.0,
        0.0,
        1.0,
        1.0,
        0.0
      ]
    },
    {
      "id": "B-7",
      "name": "BOM 신호",
      "source": "Hacker News Algolia API",
      "value": "+141.00",
      "num": 141.0,
      "tone": "pos",
      "desc": "PCB·기판 가격 (공급망 트랜스크립트)",
      "spark": [
        0.009,
        0.0,
        1.0,
        0.255,
        0.03,
        0.012,
        0.432,
        0.429
      ]
    }
  ],
  "news": [
    {
      "date": "2026-09-04",
      "title": "마이크론, SanDisk 급등 as AI 메모리 부족 Trumps Rate-Hike Fears",
      "titleEn": "Micron, SanDisk Surge as AI Memory Shortage Trumps Rate-Hike Fears",
      "source": "finance.biggo.com",
      "score": 0.67,
      "tone": "pos",
      "conf": 50,
      "hot": true,
      "summary": "마이크론, SanDisk Surge as AI Memory Shortage Trumps Rate-Hike Fears &nbsp;&nbsp; finance.biggo.com",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMidkFVX3lxTE9YT3JrZDBzb0Y1d2psWk9TUDZwNWdNclhDR3Vqd2VJQ3JJUXA3RVBHVG5IVmlfaEwyQ0llam9PNXd3cWhlNm90TzhLZWduTHhEM2FXaXIxaFc0QUNqNEVWT0xPa3VLd2J2REVaTkQzSkVaWjFDTVE?oc=5"
    },
    {
      "date": "2026-08-28",
      "title": "DDR5 가격 급등 Fivefold in a Year — 중국's HBM Obsession Creates a Legacy DR",
      "titleEn": "DDR5 Prices Surge Fivefold in a Year — China's HBM Obsession Creates a Legacy DRAM Shortage Paradox",
      "source": "finance.biggo.com",
      "score": 0.67,
      "tone": "pos",
      "conf": 50,
      "hot": true,
      "summary": "DDR5 Prices Surge Fivefold in a Year — 중국's HBM Obsession Creates a Legacy DRAM Shortage Paradox &nbsp;&nbsp; finance.biggo.com",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMidkFVX3lxTFB1bDI0eE9hSXB4V1c2Y04xWjVXbDdpd213bXNVdndoV19JSjBHWFRCMHZ2LUo1U3I3UW1UbDBFcE5WLUcyNWJYcHN3RWR4SWVaajZ2MkQwSzJzMlB1NFJqQWxwM2VVR2hKOUI1S3VFMnQ5QVRCRHc?oc=5"
    },
    {
      "date": "2026-09-16",
      "title": "AI-induced 메모리 부족 is changing how devices are built, Fairphone says 메모",
      "titleEn": "AI-induced memory shortage is changing how devices are built, Fairphone says memory now 60% of materials cost — smaller laptop and phone makers are redesigning products and have to test for fake chips - Tom's Hardware",
      "source": "RSS",
      "score": 0.5,
      "tone": "pos",
      "conf": 50,
      "hot": true,
      "summary": "AI-induced memory shortage is changing how devices are built, Fairphone says memory now 60% of materials cost — smaller laptop and phone makers are redesigning products and have to",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMi6wJBVV95cUxOS1dYNmpYUTBQd3djYlRQTEpzOXNxaWNSOElGbGd5NmptTklaUkNlNTMwR0xXa01FQWdwQ0tsVFZYR0NVcmdobkJJcW5RaG05QldZRU0yN0U4enJZOW5JSU1Mc3U2M3liOF9OdWpaQzlOUklCX1hxZG1iQV8xM0p6V3JWS1JTMmIzb1E4ZnVlV1ZITkJIUGx3U3VabWR1b3pXUXFfYVVEVTdrUGo5S3J2RzJ4aFhuVElsa25wcndnVlduQ1ZZWWw5WUg0RThvQTRaSHFqY0R1UEQtNHlnMThnLU56UWZhem43RDZUTzB0b3FPZ2N1Y2JkNlNqakFaUk9mN1l1R0VvQTdabnh0TEN4UXVJVVp0OXR6SllMMXNiT1JGTmczQjFzRjdBVTZDaFpYSjlNYUUxRUdveGxDd2RFZXk0aVRQRWhxNlpZenRlRkhaS2lwTDROd2lVYnJ4Wk1VYWF3dXhzUlB2RTA?oc=5"
    },
    {
      "date": "2026-09-17",
      "title": "AI 서버 stocks 강세 as hard전쟁e 수요 broad...",
      "titleEn": "AI server stocks rally as hardware demand broad...",
      "source": "Pluang",
      "score": 0.5,
      "tone": "pos",
      "conf": 50,
      "hot": true,
      "summary": "AI server stocks rally as hardware demand broad... &nbsp;&nbsp; Pluang",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMisAFBVV95cUxOTWlyYWxYRnBseWE4RjJLZWhKOXVlbl9RNUo4RFlnV0hMWTJGWFJFclhrU1BZeWM4UW5kTWVicDdIdXVPMFJWaXJ1TzNTTmdMa2JKbU5XSWNUYWdSekFSYWliZTZVckk2aF9kR1MxUlBhb0JCbnB5Smp6blNuTFlFVjZLY3VGRmZzaHJqekx1eEJRM3lETERTeldQb21fU2RDLWx0aUJZR2lVMm1BdEIzTQ?oc=5"
    },
    {
      "date": "2026-09-16",
      "title": "삼성 shifts 메모리 제조 focus to전쟁d AI-driven high-bandwidth 메모리",
      "titleEn": "Samsung shifts memory manufacturing focus toward AI-driven high-bandwidth memory",
      "source": "Global Sources",
      "score": -0.5,
      "tone": "neg",
      "conf": 50,
      "hot": true,
      "summary": "삼성 shifts memory manufacturing focus toward AI-driven high-bandwidth memory &nbsp;&nbsp; Global Sources",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMixgFBVV95cUxQb3JjVEVROUQ0TUJEcFh6OGdUYzdwRFFsNlh5RlJTSkJrYmRXdjd4Y0hBWWlSaXFtWmhOUjJWSVNLcE14dUFYU0RkMFJSTTh1VWFmeDlEbWZTclNsMjR6cEpFdzgxWU5seEdJQkhLSHJ0clpkSDFWMW5MTUJjRW10TTRvWlFDMENJSHV1MHZvTzlZdDVNOFlpdThtdGxVXzhOa3pfUlRkQzZydlZNYzFlVUVBSFFCeEdXVWNWWTYza2ZGOEtZOWc?oc=5"
    },
    {
      "date": "2026-09-16",
      "title": "Intel CEO 경고 of Worsening 메모리 부족",
      "titleEn": "Intel CEO Warns of Worsening Memory Shortage",
      "source": "ForkLog",
      "score": 0.5,
      "tone": "pos",
      "conf": 50,
      "hot": true,
      "summary": "Intel CEO Warns of Worsening Memory Shortage &nbsp;&nbsp; ForkLog",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMid0FVX3lxTE5JSjNFVkdxXzJuUl9HempKX3ItQ2NTWHotQkQtdHVqbTl0SkllamFvMG00UzdPemlHUmY2eEJ2MDZpSlZ5d2UzN3VNTmJVM2UwRG5tVkpodmtsY3hIOUVzVVp1a1VmVDZ4WjZnRWNWNGxTcVJnMkFZ?oc=5"
    },
    {
      "date": "2026-09-14",
      "title": "Tungsten Export Bans From Zimbabwe to Washington Are Squeezing Chipmak",
      "titleEn": "Tungsten Export Bans From Zimbabwe to Washington Are Squeezing Chipmakers",
      "source": "Startup Fortune",
      "score": -0.5,
      "tone": "neg",
      "conf": 50,
      "hot": true,
      "summary": "Tungsten Export Bans From Zimbabwe to Washington Are Squeezing Chipmakers &nbsp;&nbsp; Startup Fortune",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxOb3dyWDc1Vlc1T3Mta1p1Z3IyNXotUU9vLVF2TmhhTGhlSm1kZWVzeXJoWXF5djVUMW1MNVdpeXBKelZ0VjBpVHdkNVFxbkhOc0pwcnVRNl9kUjdNX01COFpBdE1vMTQxREZsY1ItRWw5TUdLNHpWaHlISFEwcDMtQmFiU1JkYUgtYVBwVk9RbU5fYTBBSmdJSjhGMUx5QXlTUTFR?oc=5"
    },
    {
      "date": "2026-09-11",
      "title": "엔비디아’s Export Ban Backfires as Chinese Competitors Raise 가격 50% - 24/7",
      "titleEn": "NVIDIA’s Export Ban Backfires as Chinese Competitors Raise Prices 50% - 24/7 Wall St.",
      "source": "RSS",
      "score": -0.5,
      "tone": "neg",
      "conf": 50,
      "hot": true,
      "summary": "엔비디아’s Export Ban Backfires as Chinese Competitors Raise Prices 50% &nbsp;&nbsp; 24/7 Wall St.",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMisAFBVV95cUxNd2JBZWpwa3lsVUtUbEdJZEJGNFk1eXREdnk4UHJlaHAzeDhhWGJBWXJ1SDFCSVRiR0RQeTBOd25mZS1JQlZsWFA2OE1WQnZkWVp5dXllZG4xM19YRnQ4Wjc4bVVoTG1GZFZjUEJSTGhKcm9GN1l0akFvSFhidURmN2dRZ3dVNVZyS1d0RUMwTmNWNm9vR25NRHhFS2Q3STczaG44S0FxSm5ObzE4WFVIWA?oc=5"
    },
    {
      "date": "2026-08-26",
      "title": "엔비디아 custom 'NVHBM' promises 30% higher bandwidth, 15% lower power tha",
      "titleEn": "Nvidia custom 'NVHBM' promises 30% higher bandwidth, 15% lower power than commodity HBM4e — custom base die and PHY will be available to NVLink Fusion partners - Tom's Hardware",
      "source": "RSS",
      "score": -0.5,
      "tone": "neg",
      "conf": 50,
      "hot": true,
      "summary": "엔비디아 custom 'NVHBM' promises 30% higher bandwidth, 15% lower power than commodity HBM4e — custom base die and PHY will be available to NVLink Fusion partners &nbsp;&nbsp; Tom's H",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMivAJBVV95cUxNRUFaUUtqVEh6MWJLSnZ1bTF1aXdib181blNlbzlyZjRRV0k1UXZMOE4wRFFxdVBPMTlRZG81OTFreDdiMjlDQVFhMmlYaXBkOFFpRGNCdl9oOGkyMG4zTzV6LTliN0M0bHotdnpRV0Vsb3NtelRjSFVrN3dZOXFGaEcyMFBVSGg5U1lFb0QtN3hRcTQxS1FpX1BER21yYjFZeHhlMFQzS0ROMlBlXzN3N2tkZy1DNGc4ZUltNUtlSTBOS3B1Q2tMT2VuemgtWXM3cm1fb3RXellIaVRNc3hfRG9kcFRlLUFEb24tcl9fQnlrTWYtbXBPVzQ0N25DRGo4XzhkVkVCcUNfY1J3aDhOOXI1ZW1yZFBvQkhDYTRtOHJSclJ1NXU5WnZCNElUb1RwbW5KS05fa3A2NlFI?oc=5"
    },
    {
      "date": "2026-08-28",
      "title": "New US export controls 보고edly target Chinese access to remote AI 서버s —",
      "titleEn": "New US export controls reportedly target Chinese access to remote AI servers — Trump admin's cut-down AI diffusion rule could be shared with industry as soon as September - Tom's Hardware",
      "source": "RSS",
      "score": 0.0,
      "tone": "neu",
      "conf": 50,
      "hot": false,
      "summary": "New US export controls reportedly target Chinese access to remote AI servers — Trump admin's cut-down AI diffusion rule could be shared with industry as soon as September &nbsp;&nb",
      "effects": {
        "short": {
          "tone": "neu",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "neu",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "neu",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMivgJBVV95cUxNV3RGYmw3MU9Ua3ltUW91dXBjSURjWlhYcnIxZ3A0Nkx5cVJJUEZtam1hak8zazhDeS1jRExGYzhvcHVTUmNRT3AzV2JnVjh1R09GdUlRaXgwbElHdHdxRWZ3RUREbDVHSVpYVjZOVXV3SENsWFpqSG9PQ1h0b1dVT19CaEdhbHpDSklSbmRmNC1KeWJ3Z1ZtaFhWekhpY0pBTGFPSGtmbDFqenFNVmF2NThpNm9lMWtDdmU0UHFtcEhFUnRjTmw4U1RvdVFDWVdsNTZmcmljdGlMbHB6bmM4QUJ6OXJ3VlNabU04MmVzMlUtck52ZlhFdF9CTFI0aTVTU0xNQXpKVmlwMVEzdy1pYUhBb2YyZmFBY2NTTHBaR1lfM0RwQ3gwY0NGZHc2TVBTbzFqRXdFaFgtclVpTUE?oc=5"
    }
  ],
  "macro": [
    {
      "id": "ust10",
      "name": "미국 10년물 국채금리",
      "value": "4.53%",
      "change": "↑ 부정",
      "tone": "neg",
      "desc": "FRED DGS10 (10-Year Treasury Yield, 위험자산 선호도 지표)",
      "history": [
        4.47,
        4.49,
        4.51,
        4.46,
        4.44,
        4.45,
        4.53
      ]
    },
    {
      "id": "fed",
      "name": "미국 금리",
      "value": "3.62%",
      "change": "↑ 긍정",
      "tone": "neu",
      "desc": "Effective Federal Funds Rate (FRED DFF)",
      "history": [
        3.62,
        3.62,
        3.62,
        3.63,
        3.63,
        3.63,
        3.62
      ]
    },
    {
      "id": "dxy",
      "name": "달러 인덱스 (DXY)",
      "value": "101.0",
      "change": "↑ 부정",
      "tone": "neg",
      "desc": "강달러 = DRAM 수출 부정 (DX-Y.NYB)",
      "history": [
        98.91,
        100.07,
        99.75,
        100.85,
        101.36,
        100.86,
        100.97
      ]
    },
    {
      "id": "pmi",
      "name": "산업생산지수",
      "value": "102.6",
      "change": "동결",
      "tone": "neu",
      "desc": "FRED INDPRO (PMI 대체)",
      "history": [
        102.65,
        102.65,
        102.65,
        102.65,
        102.65,
        102.65,
        102.65
      ]
    },
    {
      "id": "krw",
      "name": "USD/KRW",
      "value": "1,499",
      "change": "↓ 부정",
      "tone": "pos",
      "desc": "원화 약세 = 수입 원가↑ (Yahoo KRW=X)",
      "history": [
        1505.96,
        1557.47,
        1516.23,
        1526.01,
        1533.12,
        1527.3,
        1498.87
      ]
    },
    {
      "id": "cu",
      "name": "구리 가격",
      "value": "$6.28",
      "change": "↓ 긍정",
      "tone": "neg",
      "desc": "LME 대체 (COMEX HG=F)",
      "history": [
        6.36,
        6.26,
        6.43,
        6.35,
        6.14,
        6.17,
        6.28
      ]
    }
  ],
  "events": [
    {
      "id": "ev-1",
      "type": "국내 반도체",
      "region": "한국",
      "risk": "high",
      "title": "KOSPI Reclaims 6,700 Level, SK하이닉스 급등 4% as 파업 Crisis Resolved; SoftBank and 키오시",
      "impact": "공급↓",
      "date": "2026-09-16",
      "summary": "한국 메모리 산업 직접 이슈 — 노사 협상 결렬 등 파업 관련 보도. 메모리 공장 가동 중단 시 단기 공급 차질 가능, 가격 상승 압력. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기 영향 평가 (휴리스틱 · 국내 반도체)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 국내 반도체)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 국내 반도체)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-2",
      "type": "물리적 충돌",
      "region": "이스라엘",
      "risk": "high",
      "title": "Netanel Shukrun identified as Neveh Tzuf 테러 attack victim, IDF catches 테러ist nea",
      "impact": "공급↓",
      "date": "2026-09-20",
      "summary": "중동 군사 긴장 보도 (이스라엘) — 유가 상승 압력 + 호르무즈 해협 물류 차질 가능. DRAM 직접 영향은 제한적이나 거시 환경 악화. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기 영향 평가 (휴리스틱 · 물리적 충돌)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 물리적 충돌)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 물리적 충돌)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-4",
      "type": "금융 위기",
      "region": "미국",
      "risk": "mid",
      "title": "Stock Market Today (Sept. 17, 2026): Dow 급등 after Fed 금리 인상 decision",
      "impact": "물류↑",
      "date": "2026-09-17",
      "summary": "Fed 금리 인상 관련 보도 — 강달러/약달러 전환 → 한국 수출가격(USD 결제) 환변동 영향. DRAM CapEx 자금조달 비용 변화 가능. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 금융 위기)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-5",
      "type": "기타",
      "region": "미국",
      "risk": "low",
      "title": "AI 경고: Federal cybersecurity agencies 경고 US adversaries could use artificial int",
      "impact": "가격?",
      "date": "2026-09-18",
      "summary": "미국 기타 관련 보도 — 추가 분석 필요. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neu",
          "text": "단기 영향 평가 (휴리스틱 · 기타)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 기타)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 기타)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-6",
      "type": "금융 위기",
      "region": "미국",
      "risk": "mid",
      "title": "Fed Rate 증가 Puts Borrowers on Notice as 전쟁sh Takes Hard Line on 인플레이션 | The 10-P",
      "impact": "가격?",
      "date": "2026-09-17",
      "summary": "Fed 금리 조정 관련 보도 — 강달러/약달러 전환 → 한국 수출가격(USD 결제) 환변동 영향. DRAM CapEx 자금조달 비용 변화 가능. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neu",
          "text": "단기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 금융 위기)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-7",
      "type": "기타",
      "region": "미국",
      "risk": "low",
      "title": "Three words from Kevin 전쟁sh have Wall Street wondering how far the Fed will go w",
      "impact": "가격?",
      "date": "2026-09-18",
      "summary": "미국 기타 관련 보도 — 추가 분석 필요. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기 영향 평가 (휴리스틱 · 기타)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 기타)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 기타)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-8",
      "type": "금융 위기",
      "region": "중동",
      "risk": "mid",
      "title": "원유 가격 급등 Over 4% Following Attack on Key Middle East Export Route",
      "impact": "가격?",
      "date": "2026-09-17",
      "summary": "국제 유가 변동 보도 (중동) — 에너지/물류비 변동으로 메모리 제조원가 + 운송비 영향. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neu",
          "text": "단기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 금융 위기)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-9",
      "type": "기타",
      "region": "글로벌",
      "risk": "low",
      "title": "Commonwealth Bank 경고 as Aussie drivers face more pain as 유가s 급등",
      "impact": "가격?",
      "date": "2026-09-15",
      "summary": "글로벌 기타 관련 보도 — 추가 분석 필요. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neu",
          "text": "단기 영향 평가 (휴리스틱 · 기타)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 기타)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 기타)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-10",
      "type": "금융 위기",
      "region": "미국",
      "risk": "mid",
      "title": "Federal Reserve interest 금리 인상 may trigger another brutal move for US 국채금리s",
      "impact": "물류↑",
      "date": "2026-09-17",
      "summary": "Fed 금리 인상 관련 보도 — 강달러/약달러 전환 → 한국 수출가격(USD 결제) 환변동 영향. DRAM CapEx 자금조달 비용 변화 가능. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 금융 위기)"
        }
      },
      "links": [],
      "affects": []
    }
  ],
  "accuracy": [
    {
      "predDate": "2026-07-27",
      "horizon": "7주",
      "pred": 6.713,
      "actual": 5.986,
      "error": 12.1,
      "tone": "neg"
    },
    {
      "predDate": "2026-07-27",
      "horizon": "7주",
      "pred": 6.966,
      "actual": 6.774,
      "error": 2.8,
      "tone": "pos"
    },
    {
      "predDate": "2026-07-27",
      "horizon": "7주",
      "pred": 7.078,
      "actual": 6.877,
      "error": 2.9,
      "tone": "pos"
    },
    {
      "predDate": "2026-07-27",
      "horizon": "7주",
      "pred": 6.107,
      "actual": 6.567,
      "error": 7.0,
      "tone": "neu"
    },
    {
      "predDate": "2026-07-27",
      "horizon": "7주",
      "pred": 5.352,
      "actual": 6.894,
      "error": 22.4,
      "tone": "neg"
    },
    {
      "predDate": "2026-07-27",
      "horizon": "7주",
      "pred": 6.335,
      "actual": 6.933,
      "error": 8.6,
      "tone": "neu"
    },
    {
      "predDate": "2026-07-27",
      "horizon": "7주",
      "pred": 7.069,
      "actual": 7.154,
      "error": 1.2,
      "tone": "pos"
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 10.093,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 10.327,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 10.561,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 10.794,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 11.028,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 11.262,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 11.495,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 11.729,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 11.963,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 12.196,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 12.43,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 12.664,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 12.898,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-07-27",
      "horizon": "21주",
      "pred": 13.131,
      "actual": null,
      "error": null,
      "tone": null
    }
  ],
  "snapshotPast": {
    "date": "2026-07-27",
    "actual": 7.154,
    "predicted": 6.217,
    "error": 13.1,
    "signals": [
      {
        "id": "A-1",
        "name": "대만 공급망",
        "then": "288.2",
        "thenTone": "neu",
        "now": "311.2",
        "nowTone": "pos",
        "direction": "up",
        "change": "개선"
      },
      {
        "id": "A-2",
        "name": "빅테크 CapEx",
        "then": "165693.0",
        "thenTone": "neu",
        "now": "165693.0",
        "nowTone": "neu",
        "direction": "flat",
        "change": "유사"
      },
      {
        "id": "A-3",
        "name": "관세청 수출",
        "then": "9248046034.0",
        "thenTone": "neu",
        "now": "9248046034.0",
        "nowTone": "neu",
        "direction": "flat",
        "change": "유사"
      },
      {
        "id": "A-4",
        "name": "재고/출하 지수",
        "then": "4923610.0",
        "thenTone": "neu",
        "now": "4923610.0",
        "nowTone": "neu",
        "direction": "flat",
        "change": "유사"
      },
      {
        "id": "A-5",
        "name": "AWS Spot 가격",
        "then": "+0.12",
        "thenTone": "neu",
        "now": "+0.13",
        "nowTone": "pos",
        "direction": "up",
        "change": "개선"
      },
      {
        "id": "A-6",
        "name": "Manifold 봉쇄확률",
        "then": "+0.33",
        "thenTone": "neu",
        "now": "+0.32",
        "nowTone": "neg",
        "direction": "down",
        "change": "약화"
      },
      {
        "id": "A-7",
        "name": "구리 선물가",
        "then": "+6.25",
        "thenTone": "neu",
        "now": "+6.28",
        "nowTone": "pos",
        "direction": "up",
        "change": "개선"
      },
      {
        "id": "B-1",
        "name": "Earnings Call",
        "then": "-0.20",
        "thenTone": "neu",
        "now": "+1.00",
        "nowTone": "pos",
        "direction": "up",
        "change": "개선"
      },
      {
        "id": "B-2",
        "name": "대만 뉴스 감성",
        "then": "+0.23",
        "thenTone": "neu",
        "now": "+0.11",
        "nowTone": "neg",
        "direction": "down",
        "change": "약화"
      },
      {
        "id": "B-3",
        "name": "Reddit/HN",
        "then": "+2.00",
        "thenTone": "neu",
        "now": "+0.00",
        "nowTone": "neg",
        "direction": "down",
        "change": "약화"
      },
      {
        "id": "B-4",
        "name": "지정학 리스크",
        "then": "167.5",
        "thenTone": "neu",
        "now": "117.9",
        "nowTone": "neg",
        "direction": "down",
        "change": "약화"
      },
      {
        "id": "B-5",
        "name": "LTA 비율",
        "then": "+0.00",
        "thenTone": "neu",
        "now": "+1.00",
        "nowTone": "pos",
        "direction": "up",
        "change": "개선"
      },
      {
        "id": "B-6",
        "name": "HBM/D램 믹스",
        "then": "-0.33",
        "thenTone": "neu",
        "now": "+0.00",
        "nowTone": "pos",
        "direction": "up",
        "change": "개선"
      },
      {
        "id": "B-7",
        "name": "BOM 신호",
        "then": "30.0",
        "thenTone": "neu",
        "now": "141.0",
        "nowTone": "pos",
        "direction": "up",
        "change": "개선"
      }
    ]
  },
  "collection": {
    "summary": {
      "total": 20,
      "success": 20,
      "fail": 0,
      "newCount": 628
    },
    "week": "2026-09-20",
    "groupA": [
      {
        "id": "A-1",
        "name": "대만 공급망",
        "source": "Yahoo Finance: TSM (70%) + UMC (30%)",
        "time": "2026-07-12 06:00",
        "newItems": 56,
        "prev": 55,
        "status": "ok"
      },
      {
        "id": "A-2",
        "name": "빅테크 CapEx",
        "source": "SEC EDGAR XBRL — 4 quarterly observations from 4 c",
        "time": "2026-07-12 06:00",
        "newItems": 57,
        "prev": 56,
        "status": "ok"
      },
      {
        "id": "A-3",
        "name": "관세청 수출",
        "source": "관세청 data.go.kr Itemtrade HS 854232 (메모리) 월간 수출 (12",
        "time": "2026-09-20 06:00",
        "newItems": 57,
        "prev": 56,
        "status": "ok"
      },
      {
        "id": "A-4",
        "name": "재고/출하 지수",
        "source": "KOSIS 광공업동향 C26 재고지수 (월간→주간 forward-fill)",
        "time": "2026-09-20 06:00",
        "newItems": 57,
        "prev": 56,
        "status": "ok"
      },
      {
        "id": "A-5",
        "name": "AWS Spot 가격",
        "source": "AWS EC2 m6i.xlarge spot (us-east-1a, 최대 90일)",
        "time": "2026-09-20 06:00",
        "newItems": 13,
        "prev": 12,
        "status": "ok"
      },
      {
        "id": "A-6",
        "name": "Manifold 봉쇄확률",
        "source": "Manifold Markets 'Will China launch a full-scale i",
        "time": "2026-09-20 06:00",
        "newItems": 52,
        "prev": 51,
        "status": "ok"
      },
      {
        "id": "A-7",
        "name": "구리 선물가",
        "source": "Yahoo Finance HG=F (COMEX Copper Futures, LME 대체)",
        "time": "2026-07-12 06:00",
        "newItems": 56,
        "prev": 55,
        "status": "ok"
      }
    ],
    "groupB": [
      {
        "id": "B-1",
        "name": "Earnings Call",
        "source": "Google News 'Earnings Call sentiment' (180 entries",
        "time": "2026-09-20 06:00",
        "newItems": 22,
        "prev": 21,
        "status": "ok"
      },
      {
        "id": "B-2",
        "name": "대만 뉴스 감성",
        "source": "TechNews.tw + Digitimes + Google News RSS (1033 en",
        "time": "2026-09-20 06:00",
        "newItems": 27,
        "prev": 26,
        "status": "ok"
      },
      {
        "id": "B-3",
        "name": "Reddit/HN",
        "source": "Hacker News Algolia ('memory chip price') — Reddit",
        "time": "2026-09-20 06:00",
        "newItems": 57,
        "prev": 56,
        "status": "ok"
      },
      {
        "id": "B-4",
        "name": "지정학 리스크",
        "source": "Caldara & Iacoviello GPR Index (https://www.matteo",
        "time": "2026-09-20 06:00",
        "newItems": 57,
        "prev": 56,
        "status": "ok"
      },
      {
        "id": "B-5",
        "name": "LTA 비율",
        "source": "Google News 'LTA ratio' (84 entries, 키워드 fallback,",
        "time": "2026-09-20 06:00",
        "newItems": 19,
        "prev": 18,
        "status": "ok"
      },
      {
        "id": "B-6",
        "name": "HBM/D램 믹스",
        "source": "Google News 'HBM mix' (163 entries, 키워드 fallback, ",
        "time": "2026-09-20 06:00",
        "newItems": 41,
        "prev": 40,
        "status": "ok"
      },
      {
        "id": "B-7",
        "name": "BOM 신호",
        "source": "Hacker News Algolia API (queries: 4건)",
        "time": "2026-09-20 06:00",
        "newItems": 57,
        "prev": 56,
        "status": "ok"
      }
    ]
  }
};
