// AUTO-GENERATED by backend/pipelines/build_frontend_data.py
// DO NOT EDIT MANUALLY — regenerate via: python3 pipelines/build_frontend_data.py
// 데이터 소스: backend/data/historical/* + backend/data/forecast/forecast_v2_*.json
//             + backend/data/news/latest.json + backend/data/events/latest.json
// 생성 시각: 2026-09-14T23:55:51.159928Z
// 뉴스/이벤트: news 10건 (키워드 휴리스틱, 2026-09-14) · events 6건 (기상이변 제외)
// UI 컴포넌트는 design_handoff_sixsense_dram_dashboard 의 SIXSENSE_DATA 스키마를 그대로 따른다.

export const SIXSENSE_DATA = {
  "meta": {
    "current": 7.464,
    "currentChange": "-4.5%",
    "pred7": 9.33,
    "pred7Change": "+25.0%",
    "pred21": 8.995,
    "pred21Change": "+20.5%",
    "updated": "2026-07-12 06:00 KST",
    "model": "GBR (단기) + LSTM (중장기) + Prophet (베이스)",
    "confidence": 81,
    "insight": {
      "headline": "AI 수요 견인, **DRAM 가격** 상승 전환",
      "summary": "서버 DRAM 가격은 현재 소폭 하락했으나, 단기 및 중장기 예측 모두 **20% 이상**의 큰 폭 상승을 예고하며 강력한 상승이 기대됩니다. 핵심은 **빅테크 CapEx** 증가와 AI 메모리 부족 뉴스에서 확인되는 **AI 수요** 증가입니다. HBM 집중 레거시 DRAM 공급 부족 심화도 가격 상승 압력을 가중시킵니다. 긍정적인 산업 생산 지수와 높은 수출 실적 등 거시경제 지표도 수요를 지지합니다. 단기 예측이 중장기보다 다소 가파르지만, 전반적인 시장은 공급 부족과 수요 견인으로 인한 가격 상승 기조가 뚜렷합니다. 지정학적 리스크(GPR)와 재고/출하 지수 변화를 주시해야 합니다.",
      "tone": "pos",
      "confidence": 85,
      "horizon": "short",
      "keySignals": [
        "A-2",
        "B-4"
      ],
      "model": "Gemini gemini-2.5-flash",
      "generatedAt": "2026-09-14T23:55:51"
    },
    "modelValidation": {
      "headline": "🎉 Phase 6 멀티 모델 예측 아키텍처 완료 — 단기 MAPE 7.54% → 4.54% (39.8% 개선)",
      "shortRows": [
        {
          "model": "Prophet (기존)",
          "mape": 7.54,
          "eval": "baseline",
          "winner": false
        },
        {
          "model": "sklearn HistGBR",
          "mape": 6.86,
          "eval": "중간",
          "winner": false
        },
        {
          "model": "sklearn GBR",
          "mape": 4.54,
          "eval": "39.8% 개선",
          "winner": true
        }
      ],
      "midRows": [
        {
          "model": "LSTM (PyTorch 2-layer hidden=64)",
          "mape": 7.66
        }
      ],
      "trainTimes": [
        {
          "name": "Prophet",
          "sec": 0.87
        },
        {
          "name": "Tree (단기)",
          "sec": 2.65
        },
        {
          "name": "LSTM (중장기)",
          "sec": 6.33
        }
      ],
      "trainTotal": 9.8,
      "architecture": "20개 신호 통합 DataFrame (108주 × 20열, sentiment 3주 MA)\n            │\n   ┌────────┼────────┐\n   ▼        ▼        ▼\n[Prophet] [Tree]  [LSTM]\nbaseline  단기      중장기\n         ─우수─    PyTorch\n         자동선정   2-layer",
      "envNote": "XGBoost/LightGBM 우선 사용 시도 → macOS libomp 미설치 → sklearn GBR/HistGBR fallback 자동 전환. brew install libomp 후 자동 XGBoost/LightGBM 활성 (코드 변경 불필요). LSTM은 PyTorch (libomp 무관, 즉시 작동)."
    }
  },
  "history": [
    {
      "week": -51,
      "value": 1.002,
      "type": "actual"
    },
    {
      "week": -50,
      "value": 0.982,
      "type": "actual"
    },
    {
      "week": -49,
      "value": 0.957,
      "type": "actual"
    },
    {
      "week": -48,
      "value": 1.022,
      "type": "actual"
    },
    {
      "week": -47,
      "value": 1.052,
      "type": "actual"
    },
    {
      "week": -46,
      "value": 1.009,
      "type": "actual"
    },
    {
      "week": -45,
      "value": 1.03,
      "type": "actual"
    },
    {
      "week": -44,
      "value": 1.084,
      "type": "actual"
    },
    {
      "week": -43,
      "value": 1.273,
      "type": "actual"
    },
    {
      "week": -42,
      "value": 1.343,
      "type": "actual"
    },
    {
      "week": -41,
      "value": 1.309,
      "type": "actual"
    },
    {
      "week": -40,
      "value": 1.523,
      "type": "actual"
    },
    {
      "week": -39,
      "value": 1.552,
      "type": "actual"
    },
    {
      "week": -38,
      "value": 1.691,
      "type": "actual"
    },
    {
      "week": -37,
      "value": 1.813,
      "type": "actual"
    },
    {
      "week": -36,
      "value": 1.919,
      "type": "actual"
    },
    {
      "week": -35,
      "value": 1.969,
      "type": "actual"
    },
    {
      "week": -34,
      "value": 1.979,
      "type": "actual"
    },
    {
      "week": -33,
      "value": 1.766,
      "type": "actual"
    },
    {
      "week": -32,
      "value": 1.913,
      "type": "actual"
    },
    {
      "week": -31,
      "value": 1.959,
      "type": "actual"
    },
    {
      "week": -30,
      "value": 2.008,
      "type": "actual"
    },
    {
      "week": -29,
      "value": 2.072,
      "type": "actual"
    },
    {
      "week": -28,
      "value": 2.245,
      "type": "actual"
    },
    {
      "week": -27,
      "value": 2.498,
      "type": "actual"
    },
    {
      "week": -26,
      "value": 2.732,
      "type": "actual"
    },
    {
      "week": -25,
      "value": 2.85,
      "type": "actual"
    },
    {
      "week": -24,
      "value": 3.023,
      "type": "actual"
    },
    {
      "week": -23,
      "value": 3.279,
      "type": "actual"
    },
    {
      "week": -22,
      "value": 3.109,
      "type": "actual"
    },
    {
      "week": -21,
      "value": 3.302,
      "type": "actual"
    },
    {
      "week": -20,
      "value": 3.479,
      "type": "actual"
    },
    {
      "week": -19,
      "value": 3.634,
      "type": "actual"
    },
    {
      "week": -18,
      "value": 3.209,
      "type": "actual"
    },
    {
      "week": -17,
      "value": 3.403,
      "type": "actual"
    },
    {
      "week": -16,
      "value": 3.556,
      "type": "actual"
    },
    {
      "week": -15,
      "value": 3.14,
      "type": "actual"
    },
    {
      "week": -14,
      "value": 3.13,
      "type": "actual"
    },
    {
      "week": -13,
      "value": 3.593,
      "type": "actual"
    },
    {
      "week": -12,
      "value": 3.884,
      "type": "actual"
    },
    {
      "week": -11,
      "value": 4.174,
      "type": "actual"
    },
    {
      "week": -10,
      "value": 4.436,
      "type": "actual"
    },
    {
      "week": -9,
      "value": 5.892,
      "type": "actual"
    },
    {
      "week": -8,
      "value": 5.964,
      "type": "actual"
    },
    {
      "week": -7,
      "value": 6.287,
      "type": "actual"
    },
    {
      "week": -6,
      "value": 7.717,
      "type": "actual"
    },
    {
      "week": -5,
      "value": 7.017,
      "type": "actual"
    },
    {
      "week": -4,
      "value": 7.565,
      "type": "actual"
    },
    {
      "week": -3,
      "value": 9.004,
      "type": "actual"
    },
    {
      "week": -2,
      "value": 8.842,
      "type": "actual"
    },
    {
      "week": -1,
      "value": 7.818,
      "type": "actual"
    },
    {
      "week": 0,
      "value": 7.464,
      "type": "actual"
    }
  ],
  "forecast7": [
    {
      "week": 1,
      "value": 7.464,
      "lower": 7.091,
      "upper": 7.837,
      "type": "f7"
    },
    {
      "week": 2,
      "value": 7.889,
      "lower": 7.495,
      "upper": 8.283,
      "type": "f7"
    },
    {
      "week": 3,
      "value": 8.323,
      "lower": 7.907,
      "upper": 8.739,
      "type": "f7"
    },
    {
      "week": 4,
      "value": 8.536,
      "lower": 8.109,
      "upper": 8.963,
      "type": "f7"
    },
    {
      "week": 5,
      "value": 8.811,
      "lower": 8.37,
      "upper": 9.252,
      "type": "f7"
    },
    {
      "week": 6,
      "value": 9.068,
      "lower": 8.615,
      "upper": 9.521,
      "type": "f7"
    },
    {
      "week": 7,
      "value": 9.33,
      "lower": 8.864,
      "upper": 9.796,
      "type": "f7"
    }
  ],
  "forecast21": [
    {
      "week": 8,
      "value": 9.33,
      "lower": 8.397,
      "upper": 10.263,
      "type": "f21"
    },
    {
      "week": 9,
      "value": 10.407,
      "lower": 9.366,
      "upper": 11.448,
      "type": "f21"
    },
    {
      "week": 10,
      "value": 11.042,
      "lower": 9.938,
      "upper": 12.146,
      "type": "f21"
    },
    {
      "week": 11,
      "value": 10.984,
      "lower": 9.886,
      "upper": 12.082,
      "type": "f21"
    },
    {
      "week": 12,
      "value": 10.646,
      "lower": 9.581,
      "upper": 11.711,
      "type": "f21"
    },
    {
      "week": 13,
      "value": 9.899,
      "lower": 8.909,
      "upper": 10.889,
      "type": "f21"
    },
    {
      "week": 14,
      "value": 9.48,
      "lower": 8.532,
      "upper": 10.428,
      "type": "f21"
    },
    {
      "week": 15,
      "value": 8.937,
      "lower": 8.043,
      "upper": 9.831,
      "type": "f21"
    },
    {
      "week": 16,
      "value": 9.097,
      "lower": 8.187,
      "upper": 10.007,
      "type": "f21"
    },
    {
      "week": 17,
      "value": 9.155,
      "lower": 8.239,
      "upper": 10.071,
      "type": "f21"
    },
    {
      "week": 18,
      "value": 9.162,
      "lower": 8.246,
      "upper": 10.078,
      "type": "f21"
    },
    {
      "week": 19,
      "value": 9.09,
      "lower": 8.181,
      "upper": 9.999,
      "type": "f21"
    },
    {
      "week": 20,
      "value": 8.937,
      "lower": 8.043,
      "upper": 9.831,
      "type": "f21"
    },
    {
      "week": 21,
      "value": 8.995,
      "lower": 8.095,
      "upper": 9.895,
      "type": "f21"
    }
  ],
  "forecast_prophet": [
    {
      "week": 1,
      "value": 7.464,
      "type": "prophet"
    },
    {
      "week": 2,
      "value": 7.695,
      "type": "prophet"
    },
    {
      "week": 3,
      "value": 7.925,
      "type": "prophet"
    },
    {
      "week": 4,
      "value": 8.156,
      "type": "prophet"
    },
    {
      "week": 5,
      "value": 8.387,
      "type": "prophet"
    },
    {
      "week": 6,
      "value": 8.617,
      "type": "prophet"
    },
    {
      "week": 7,
      "value": 8.848,
      "type": "prophet"
    },
    {
      "week": 8,
      "value": 9.079,
      "type": "prophet"
    },
    {
      "week": 9,
      "value": 9.309,
      "type": "prophet"
    },
    {
      "week": 10,
      "value": 9.54,
      "type": "prophet"
    },
    {
      "week": 11,
      "value": 9.77,
      "type": "prophet"
    },
    {
      "week": 12,
      "value": 10.001,
      "type": "prophet"
    },
    {
      "week": 13,
      "value": 10.232,
      "type": "prophet"
    },
    {
      "week": 14,
      "value": 10.462,
      "type": "prophet"
    },
    {
      "week": 15,
      "value": 10.693,
      "type": "prophet"
    },
    {
      "week": 16,
      "value": 10.924,
      "type": "prophet"
    },
    {
      "week": 17,
      "value": 11.154,
      "type": "prophet"
    },
    {
      "week": 18,
      "value": 11.385,
      "type": "prophet"
    },
    {
      "week": 19,
      "value": 11.616,
      "type": "prophet"
    },
    {
      "week": 20,
      "value": 11.846,
      "type": "prophet"
    },
    {
      "week": 21,
      "value": 12.077,
      "type": "prophet"
    }
  ],
  "forecast_histgbr": [
    {
      "week": 1,
      "value": 7.464,
      "type": "histgbr"
    },
    {
      "week": 2,
      "value": 9.127,
      "type": "histgbr"
    },
    {
      "week": 3,
      "value": 9.16,
      "type": "histgbr"
    },
    {
      "week": 4,
      "value": 8.333,
      "type": "histgbr"
    },
    {
      "week": 5,
      "value": 8.334,
      "type": "histgbr"
    },
    {
      "week": 6,
      "value": 8.984,
      "type": "histgbr"
    },
    {
      "week": 7,
      "value": 8.984,
      "type": "histgbr"
    }
  ],
  "signalsA": [
    {
      "id": "A-1",
      "name": "대만 공급망",
      "source": "Yahoo Finance: TSM",
      "value": "+2.6%",
      "num": 0.0262,
      "tone": "neu",
      "desc": "TSMC·UMC 주가 (Yahoo Finance 블렌드)",
      "spark": [
        0.0,
        0.26,
        0.188,
        0.347,
        1.0,
        0.515,
        0.538,
        0.536
      ]
    },
    {
      "id": "A-3",
      "name": "관세청 수출",
      "source": "관세청 data.go.kr Itemtrade HS 854232",
      "value": "9248.05M",
      "num": 9248046034.0,
      "tone": "neu",
      "desc": "메모리 반도체 수출액 (관세청 Open API)",
      "spark": [
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5
      ]
    },
    {
      "id": "A-4",
      "name": "재고/출하 지수",
      "source": "KOSIS 광공업동향 C26 재고지수",
      "value": "4.92M",
      "num": 4923610.0,
      "tone": "alert",
      "desc": "100 초과 = 공급과잉 (KOSIS Open API)",
      "spark": [
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5
      ]
    },
    {
      "id": "A-5",
      "name": "AWS Spot 가격",
      "source": "AWS EC2 m6i.xlarge spot",
      "value": "$0.13",
      "num": 0.1326,
      "tone": "pos",
      "desc": "p4d.24xlarge 시간당 (AWS Pricing API)",
      "spark": [
        0.268,
        0.0,
        0.211,
        0.136,
        0.173,
        0.481,
        0.815,
        1.0
      ]
    },
    {
      "id": "A-6",
      "name": "Manifold 봉쇄확률",
      "source": "Manifold Markets 'Will China launch a fu",
      "value": "28%",
      "num": 0.2807,
      "tone": "neu",
      "desc": "대만 침공 확률 (Manifold Markets)",
      "spark": [
        1.0,
        0.986,
        0.807,
        0.839,
        0.811,
        0.554,
        0.0,
        0.071
      ]
    },
    {
      "id": "A-7",
      "name": "구리 선물가",
      "source": "Yahoo Finance HG=F",
      "value": "$6.28",
      "num": 6.282,
      "tone": "neu",
      "desc": "10주 선행 → DRAM (COMEX HG=F)",
      "spark": [
        0.694,
        0.754,
        0.422,
        1.0,
        0.735,
        0.0,
        0.104,
        0.486
      ]
    }
  ],
  "signalsB": [
    {
      "id": "B-1",
      "name": "Earnings Call",
      "source": "Google News 'Earnings Call sentiment'",
      "value": "+0.00",
      "num": 0.0,
      "tone": "neu",
      "desc": "메모리 4사 콜 감성 (Google News+LLM)",
      "spark": [
        0.5,
        0.75,
        0.5,
        0.5,
        1.0,
        1.0,
        0.0,
        0.5
      ]
    },
    {
      "id": "B-5",
      "name": "LTA 비율",
      "source": "Google News 'LTA ratio'",
      "value": "+0.00",
      "num": 0.0,
      "tone": "neu",
      "desc": "장기 계약가/현물가 (DRAMeXchange)",
      "spark": [
        0.5,
        0.0,
        0.5,
        0.5,
        0.5,
        1.0,
        0.5,
        0.5
      ]
    },
    {
      "id": "B-6",
      "name": "HBM/D램 믹스",
      "source": "Google News 'HBM mix'",
      "value": "-1.00",
      "num": -1.0,
      "tone": "neg",
      "desc": "HBM 비중 변화 (TrendForce)",
      "spark": [
        0.15,
        1.0,
        0.5,
        0.5,
        0.95,
        1.0,
        1.0,
        0.0
      ]
    },
    {
      "id": "B-7",
      "name": "BOM 신호",
      "source": "Hacker News Algolia API",
      "value": "+0.00",
      "num": 0.0,
      "tone": "neu",
      "desc": "PCB·기판 가격 (공급망 트랜스크립트)",
      "spark": [
        0.009,
        0.0,
        1.0,
        0.255,
        0.03,
        0.012,
        0.611,
        0.0
      ]
    }
  ],
  "news": [
    {
      "date": "2026-09-04",
      "title": "마이크론, SanDisk 급등 as AI 메모리 부족 Trumps Rate-Hike Fears",
      "titleEn": "Micron, SanDisk Surge as AI Memory Shortage Trumps Rate-Hike Fears",
      "source": "finance.biggo.com",
      "score": 0.67,
      "tone": "pos",
      "conf": 50,
      "hot": true,
      "summary": "마이크론, SanDisk 급등 as AI 메모리 부족 Trumps Rate-Hike Fears &nbsp;&nbsp; finance.biggo.com",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMidkFVX3lxTE9YT3JrZDBzb0Y1d2psWk9TUDZwNWdNclhDR3Vqd2VJQ3JJUXA3RVBHVG5IVmlfaEwyQ0llam9PNXd3cWhlNm90TzhLZWduTHhEM2FXaXIxaFc0QUNqNEVWT0xPa3VLd2J2REVaTkQzSkVaWjFDTVE?oc=5"
    },
    {
      "date": "2026-08-28",
      "title": "DDR5 가격 급등 Fivefold in a Year — 중국's HBM Obsession Creates a Legacy DR",
      "titleEn": "DDR5 Prices Surge Fivefold in a Year — China's HBM Obsession Creates a Legacy DRAM Shortage Paradox",
      "source": "finance.biggo.com",
      "score": 0.67,
      "tone": "pos",
      "conf": 50,
      "hot": true,
      "summary": "DDR5 가격 급등 Fivefold in a Year — 중국's HBM Obsession Creates a Legacy DRAM 부족 Paradox &nbsp;&nbsp; finance.biggo.com",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMidkFVX3lxTFB1bDI0eE9hSXB4V1c2Y04xWjVXbDdpd213bXNVdndoV19JSjBHWFRCMHZ2LUo1U3I3UW1UbDBFcE5WLUcyNWJYcHN3RWR4SWVaajZ2MkQwSzJzMlB1NFJqQWxwM2VVR2hKOUI1S3VFMnQ5QVRCRHc?oc=5"
    },
    {
      "date": "2026-09-11",
      "title": "Exceleram 경고 of escalating 메모리 부족",
      "titleEn": "Exceleram warns of escalating memory shortages",
      "source": "OC3D",
      "score": 0.5,
      "tone": "pos",
      "conf": 50,
      "hot": true,
      "summary": "Exceleram 경고 of escalating 메모리 부족 &nbsp;&nbsp; OC3D",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxNTThTUHA3SXdpc3hrRUUyNndvZlk2MWpkU3dNUFBib0ZQajA3T1ZfbDhOTjE0RnZSTFZSVXBCMC02aTN1LWo3YUlIdUFaZlpMUnpYaHJNYi1URlhab0YyeGFfM1FZdXEyQkVCSFBWUGRQRHZuMGhkT1pWLWNOYVpzUEhiSU1ic3Nrc3RB?oc=5"
    },
    {
      "date": "2026-09-11",
      "title": "엔비디아’s Export Ban Backfires as Chinese Competitors Raise 가격 50% - 247w",
      "titleEn": "NVIDIA’s Export Ban Backfires as Chinese Competitors Raise Prices 50% - 247wallst.com",
      "source": "RSS",
      "score": -0.5,
      "tone": "neg",
      "conf": 50,
      "hot": true,
      "summary": "엔비디아’s Export Ban Backfires as Chinese Competitors Raise 가격 50% &nbsp;&nbsp; 247wallst.com",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMisAFBVV95cUxNd2JBZWpwa3lsVUtUbEdJZEJGNFk1eXREdnk4UHJlaHAzeDhhWGJBWXJ1SDFCSVRiR0RQeTBOd25mZS1JQlZsWFA2OE1WQnZkWVp5dXllZG4xM19YRnQ4Wjc4bVVoTG1GZFZjUEJSTGhKcm9GN1l0akFvSFhidURmN2dRZ3dVNVZyS1d0RUMwTmNWNm9vR25NRHhFS2Q3STczaG44S0FxSm5ObzE4WFVIWA?oc=5"
    },
    {
      "date": "2026-09-11",
      "title": "Exceleram 경고 RAM 부족 is still escalating",
      "titleEn": "Exceleram warns RAM shortage is still escalating",
      "source": "KitGuru",
      "score": 0.5,
      "tone": "pos",
      "conf": 50,
      "hot": true,
      "summary": "Exceleram 경고 RAM 부족 is still escalating &nbsp;&nbsp; KitGuru",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "pos",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxQM0FtSUdJc0R6ckV1UmFkUmk5WUtUZUNwOUxJS2NGMl9pNnhoMTludFo0V3NMdXBZdl9MRzcwRzk4SjhwZ1JON1d3R0EzZkZ3LVg2a1VrUDFlQ0dCYS1JYndORGVyZUdqUDc4M0ZXNlgxalQzX25nLXk0ZlRZS3RzcHkwRE8xcDhzWUNjQTdRZlhqMlIxUU8yc1FleDBtMTYybV9GTzc2bGNtZw?oc=5"
    },
    {
      "date": "2026-09-02",
      "title": "마이크론 says tightly 쿠데타led DRAM could deliver more than 10x HBM bandwidt",
      "titleEn": "Micron says tightly coupled DRAM could deliver more than 10x HBM bandwidth",
      "source": "digitimes",
      "score": -0.5,
      "tone": "neg",
      "conf": 50,
      "hot": true,
      "summary": "마이크론 says tightly 쿠데타led DRAM could deliver more than 10x HBM bandwidth &nbsp;&nbsp; digitimes",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxPeEs2ejhUaFhQbk9qZGxkWWhuSG9rdE5MWWhWNUhHY2lQMlRvNXJNR0dGWXI4ZGJwT2xWU29kb2VaYXpiMkFZQ0d3ZU03SHEtOU44V2R6S2dBQVlhcWtsVFVDLVY1eXM5bjE0WmItZ2JIdHIwTVJyeFVHOXMxSzVEUzFtVS0tYjRB?oc=5"
    },
    {
      "date": "2026-08-28",
      "title": "엔비디아 NVHBM: Up to 30 percent more bandwidth and 25 percent more comput",
      "titleEn": "NVIDIA NVHBM: Up to 30 percent more bandwidth and 25 percent more compute area for custom AI chips",
      "source": "igorslab.de",
      "score": -0.5,
      "tone": "neg",
      "conf": 50,
      "hot": true,
      "summary": "엔비디아 NVHBM: Up to 30 percent more bandwidth and 25 percent more compute area for custom AI 칩s &nbsp;&nbsp; igorslab.de",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "neg",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMijAFBVV95cUxPUDZtX09ONGRUSktmamtFZzJVOGlfOHFMLWNnOERkTG16UWVPcWVnRjNTUy0wTktzbmVkRlIzVWpockRYdGpXUkxxTzJHbFZ6dUl0bmQ3Ym14OFhJalVNNHlXLXpDaGFhQ1RNeGlTZV9DaldsVENfQkxySWExeUh4aGF3bXhqMUhFWGhnMw?oc=5"
    },
    {
      "date": "2026-09-08",
      "title": "“엔비디아 Is Hamstrung Too”: Packaging Emerges as AI Chips’ New Bottleneck",
      "titleEn": "“Nvidia Is Hamstrung Too”: Packaging Emerges as AI Chips’ New Bottleneck, Intensifying Global Capex Race",
      "source": "economy.ac",
      "score": 0.0,
      "tone": "neu",
      "conf": 50,
      "hot": false,
      "summary": "“엔비디아 Is Hamstrung Too”: Packaging Emerges as AI Chips’ New Bottleneck, Intensifying Global Capex Race &nbsp;&nbsp; economy.ac",
      "effects": {
        "short": {
          "tone": "neu",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "neu",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "neu",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMiV0FVX3lxTFBGY3NZZm1keDlNaXB2dzlHTWdSR3UxSDBucktFOEhfcGpsNk9vRTdicDFkNlFMUGdsdklCeFNuUzNyczFadUZoR3lNaDVyZHAzQzNMVHlaQQ?oc=5"
    },
    {
      "date": "2026-09-08",
      "title": "Tech enthusiast finds $12,000 stack of RAM in their garage — work let ",
      "titleEn": "Tech enthusiast finds $12,000 stack of RAM in their garage — work let them keep an old server stuffed with 1,920GB of DDR4 - Tom's Hardware",
      "source": "RSS",
      "score": 0.0,
      "tone": "neu",
      "conf": 50,
      "hot": false,
      "summary": "Tech enthusiast finds $12,000 stack of RAM in their garage — work let them keep an old 서버 stuffed with 1,920GB of DDR4 &nbsp;&nbsp; Tom's Hard전쟁e",
      "effects": {
        "short": {
          "tone": "neu",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "neu",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "neu",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMi_wFBVV95cUxPX2xsTTEtRmdfeDZaWTI2REpxNmlGYjlzanduWWJhMHdhT2Y3YTBVMElyTjc2cFQ4dGxfT3JoMTl6M1NZZzRCdGliODg5WF9nMFRHaUZLZWlnT1pKbURhS2w2WFZwX3REaE1uWXlSMnFjd0w5WU1qSjFaSDBvenNveWlqYzc2WmdOd0c4aGZQVVdhdDBYeUJWVVpQVEpoUW56d2pNLTNESlB6MXF3YlNrNVUwVU5fMUV3Wnc2SjJoSGM3UzNDdXduYTB0NTZCdHV1eW9iT2dJWEVVSWlpbmlKWGZtbkNudnJxUWpDcjhscjA2aks5TEhjSk9uSnJVUmM?oc=5"
    },
    {
      "date": "2026-08-28",
      "title": "New US export controls 보고edly target Chinese access to remote AI 서버s —",
      "titleEn": "New US export controls reportedly target Chinese access to remote AI servers — Trump admin's cut-down AI diffusion rule could be shared with industry as soon as September - Tom's Hardware",
      "source": "RSS",
      "score": 0.0,
      "tone": "neu",
      "conf": 50,
      "hot": false,
      "summary": "New US export controls 보고edly target Chinese access to remote AI 서버s — Trump admin's cut-down AI diffusion rule could be shared with industry as soon as September &nbsp;&nb",
      "effects": {
        "short": {
          "tone": "neu",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "mid": {
          "tone": "neu",
          "text": "LLM 비활성 — 휴리스틱 분류"
        },
        "long": {
          "tone": "neu",
          "text": "LLM 비활성 — 휴리스틱 분류"
        }
      },
      "linked": [],
      "link": "https://news.google.com/rss/articles/CBMivgJBVV95cUxNV3RGYmw3MU9Ua3ltUW91dXBjSURjWlhYcnIxZ3A0Nkx5cVJJUEZtam1hak8zazhDeS1jRExGYzhvcHVTUmNRT3AzV2JnVjh1R09GdUlRaXgwbElHdHdxRWZ3RUREbDVHSVpYVjZOVXV3SENsWFpqSG9PQ1h0b1dVT19CaEdhbHpDSklSbmRmNC1KeWJ3Z1ZtaFhWekhpY0pBTGFPSGtmbDFqenFNVmF2NThpNm9lMWtDdmU0UHFtcEhFUnRjTmw4U1RvdVFDWVdsNTZmcmljdGlMbHB6bmM4QUJ6OXJ3VlNabU04MmVzMlUtck52ZlhFdF9CTFI0aTVTU0xNQXpKVmlwMVEzdy1pYUhBb2YyZmFBY2NTTHBaR1lfM0RwQ3gwY0NGZHc2TVBTbzFqRXdFaFgtclVpTUE?oc=5"
    }
  ],
  "macro": [
    {
      "id": "ust10",
      "name": "미국 10년물 국채금리",
      "value": "4.53%",
      "change": "↑ 부정",
      "tone": "neg",
      "desc": "FRED DGS10 (10-Year Treasury Yield, 위험자산 선호도 지표)",
      "history": [
        4.47,
        4.49,
        4.51,
        4.46,
        4.44,
        4.45,
        4.53
      ]
    },
    {
      "id": "fed",
      "name": "미국 금리",
      "value": "3.62%",
      "change": "↑ 긍정",
      "tone": "neu",
      "desc": "Effective Federal Funds Rate (FRED DFF)",
      "history": [
        3.62,
        3.62,
        3.62,
        3.63,
        3.63,
        3.63,
        3.62
      ]
    },
    {
      "id": "dxy",
      "name": "달러 인덱스 (DXY)",
      "value": "101.0",
      "change": "↑ 부정",
      "tone": "neg",
      "desc": "강달러 = DRAM 수출 부정 (DX-Y.NYB)",
      "history": [
        98.91,
        100.07,
        99.75,
        100.85,
        101.36,
        100.86,
        100.97
      ]
    },
    {
      "id": "pmi",
      "name": "산업생산지수",
      "value": "102.6",
      "change": "동결",
      "tone": "neu",
      "desc": "FRED INDPRO (PMI 대체)",
      "history": [
        102.65,
        102.65,
        102.65,
        102.65,
        102.65,
        102.65,
        102.65
      ]
    },
    {
      "id": "krw",
      "name": "USD/KRW",
      "value": "1,499",
      "change": "↓ 부정",
      "tone": "pos",
      "desc": "원화 약세 = 수입 원가↑ (Yahoo KRW=X)",
      "history": [
        1505.96,
        1557.47,
        1516.23,
        1526.01,
        1533.12,
        1527.3,
        1498.87
      ]
    },
    {
      "id": "cu",
      "name": "구리 가격",
      "value": "$6.28",
      "change": "↓ 긍정",
      "tone": "neg",
      "desc": "LME 대체 (COMEX HG=F)",
      "history": [
        6.36,
        6.26,
        6.43,
        6.35,
        6.14,
        6.17,
        6.28
      ]
    }
  ],
  "events": [
    {
      "id": "ev-1",
      "type": "국내 반도체",
      "region": "한국",
      "risk": "mid",
      "title": "[모니터링] 한국 메모리 산업 이슈 추적 (파업/정전/화재)",
      "impact": "공급↓",
      "date": "2026-08-15",
      "summary": "관련 헤드라인 미수집 (RSS 30일 윈도우 외) — 다음 주 수집 대기. (카테고리: 국내 반도체)",
      "effects": {
        "short": {
          "tone": "neu",
          "text": "(placeholder)"
        },
        "mid": {
          "tone": "neu",
          "text": "(placeholder)"
        },
        "long": {
          "tone": "neu",
          "text": "(placeholder)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-2",
      "type": "물리적 충돌",
      "region": "우크라이나",
      "risk": "high",
      "title": "Trump calls on 우크라이나 to halt 파업 on 러시아n diesel fuel, citing a global 부족",
      "impact": "공급↓",
      "date": "2026-09-14",
      "summary": "우크라이나 분쟁 관련 보도 — 글로벌 공급망 리스크 프리미엄 상승 및 에너지/원자재 가격 변동성 확대 가능. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기 영향 평가 (휴리스틱 · 물리적 충돌)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 물리적 충돌)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 물리적 충돌)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-4",
      "type": "금융 위기",
      "region": "이란",
      "risk": "high",
      "title": "유가s 급등 as 미국 and 이란 Exchange 파업 - 원유 가격 Today | 유가가격.com",
      "impact": "가격?",
      "date": "2026-08-30",
      "summary": "국제 유가 변동 보도 (이란) — 에너지/물류비 변동으로 메모리 제조원가 + 운송비 영향. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neu",
          "text": "단기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 금융 위기)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-5",
      "type": "기타",
      "region": "글로벌",
      "risk": "low",
      "title": "AI 경고s Weigh on Global Stocks as 유가s 급등 Again",
      "impact": "가격?",
      "date": "2026-09-14",
      "summary": "글로벌 기타 관련 보도 — 추가 분석 필요. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neu",
          "text": "단기 영향 평가 (휴리스틱 · 기타)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 기타)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 기타)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-7",
      "type": "금융 위기",
      "region": "미국",
      "risk": "mid",
      "title": "Trump turns up the heat on 전쟁sh as Fed 금리 인상 looms",
      "impact": "물류↑",
      "date": "2026-09-05",
      "summary": "Fed 금리 인상 관련 보도 — 강달러/약달러 전환 → 한국 수출가격(USD 결제) 환변동 영향. DRAM CapEx 자금조달 비용 변화 가능. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 금융 위기)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-9",
      "type": "금융 위기",
      "region": "미국",
      "risk": "mid",
      "title": "What a Fed 금리 인상 Actually Means for the US Economy and 인플레이션",
      "impact": "물류↑",
      "date": "2026-09-10",
      "summary": "Fed 금리 인상 관련 보도 — 강달러/약달러 전환 → 한국 수출가격(USD 결제) 환변동 영향. DRAM CapEx 자금조달 비용 변화 가능. (LLM 비활성 — 휴리스틱 요약)",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "mid": {
          "tone": "neu",
          "text": "중기 영향 평가 (휴리스틱 · 금융 위기)"
        },
        "long": {
          "tone": "neu",
          "text": "장기 영향 평가 (휴리스틱 · 금융 위기)"
        }
      },
      "links": [],
      "affects": []
    }
  ],
  "accuracy": [
    {
      "predDate": "2026-05-18",
      "horizon": "7주",
      "pred": 5.25,
      "actual": 7.717,
      "error": 32.0,
      "tone": "neg"
    },
    {
      "predDate": "2026-05-18",
      "horizon": "7주",
      "pred": 5.412,
      "actual": 7.017,
      "error": 22.9,
      "tone": "neg"
    },
    {
      "predDate": "2026-05-18",
      "horizon": "7주",
      "pred": 5.574,
      "actual": 7.565,
      "error": 26.3,
      "tone": "neg"
    },
    {
      "predDate": "2026-05-18",
      "horizon": "7주",
      "pred": 5.737,
      "actual": 9.004,
      "error": 36.3,
      "tone": "neg"
    },
    {
      "predDate": "2026-05-18",
      "horizon": "7주",
      "pred": 5.899,
      "actual": 8.842,
      "error": 33.3,
      "tone": "neg"
    },
    {
      "predDate": "2026-05-18",
      "horizon": "7주",
      "pred": 6.061,
      "actual": 7.818,
      "error": 22.5,
      "tone": "neg"
    },
    {
      "predDate": "2026-05-18",
      "horizon": "7주",
      "pred": 6.223,
      "actual": 7.464,
      "error": 16.6,
      "tone": "neg"
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 6.385,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 6.548,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 6.71,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 6.872,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 7.034,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 7.197,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 7.359,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 7.521,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 7.683,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 7.846,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 8.008,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 8.17,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 8.332,
      "actual": null,
      "error": null,
      "tone": null
    },
    {
      "predDate": "2026-05-18",
      "horizon": "21주",
      "pred": 8.495,
      "actual": null,
      "error": null,
      "tone": null
    }
  ],
  "snapshotPast": {
    "date": "2026-05-18",
    "actual": 7.464,
    "predicted": 6.287,
    "error": 15.8,
    "signals": [
      {
        "id": "A-1",
        "name": "대만 공급망",
        "then": "288.2",
        "thenTone": "neu",
        "now": "311.2",
        "nowTone": "pos",
        "direction": "up",
        "change": "개선"
      },
      {
        "id": "A-2",
        "name": "빅테크 CapEx",
        "then": "165693.0",
        "thenTone": "neu",
        "now": "165693.0",
        "nowTone": "neu",
        "direction": "flat",
        "change": "유사"
      },
      {
        "id": "A-3",
        "name": "관세청 수출",
        "then": "9248046034.0",
        "thenTone": "neu",
        "now": "9248046034.0",
        "nowTone": "neu",
        "direction": "flat",
        "change": "유사"
      },
      {
        "id": "A-4",
        "name": "재고/출하 지수",
        "then": "4923610.0",
        "thenTone": "neu",
        "now": "4923610.0",
        "nowTone": "neu",
        "direction": "flat",
        "change": "유사"
      },
      {
        "id": "A-5",
        "name": "AWS Spot 가격",
        "then": "+0.12",
        "thenTone": "neu",
        "now": "+0.13",
        "nowTone": "pos",
        "direction": "up",
        "change": "개선"
      },
      {
        "id": "A-6",
        "name": "Manifold 봉쇄확률",
        "then": "+0.33",
        "thenTone": "neu",
        "now": "+0.28",
        "nowTone": "neg",
        "direction": "down",
        "change": "약화"
      },
      {
        "id": "A-7",
        "name": "구리 선물가",
        "then": "+6.25",
        "thenTone": "neu",
        "now": "+6.28",
        "nowTone": "pos",
        "direction": "up",
        "change": "개선"
      },
      {
        "id": "B-1",
        "name": "Earnings Call",
        "then": "-0.20",
        "thenTone": "neu",
        "now": "+0.00",
        "nowTone": "pos",
        "direction": "up",
        "change": "개선"
      },
      {
        "id": "B-2",
        "name": "대만 뉴스 감성",
        "then": "+0.17",
        "thenTone": "neu",
        "now": "+0.12",
        "nowTone": "neg",
        "direction": "down",
        "change": "약화"
      },
      {
        "id": "B-3",
        "name": "Reddit/HN",
        "then": "+2.00",
        "thenTone": "neu",
        "now": "+0.00",
        "nowTone": "neg",
        "direction": "down",
        "change": "약화"
      },
      {
        "id": "B-4",
        "name": "지정학 리스크",
        "then": "167.5",
        "thenTone": "neu",
        "now": "117.9",
        "nowTone": "neg",
        "direction": "down",
        "change": "약화"
      },
      {
        "id": "B-5",
        "name": "LTA 비율",
        "then": "+0.00",
        "thenTone": "neu",
        "now": "+0.00",
        "nowTone": "neu",
        "direction": "flat",
        "change": "유사"
      },
      {
        "id": "B-6",
        "name": "HBM/D램 믹스",
        "then": "-0.80",
        "thenTone": "neu",
        "now": "-1.00",
        "nowTone": "neg",
        "direction": "down",
        "change": "약화"
      },
      {
        "id": "B-7",
        "name": "BOM 신호",
        "then": "30.0",
        "thenTone": "neu",
        "now": "+0.00",
        "nowTone": "neg",
        "direction": "down",
        "change": "약화"
      }
    ]
  },
  "collection": {
    "summary": {
      "total": 20,
      "success": 20,
      "fail": 0,
      "newCount": 638
    },
    "week": "2026-07-12",
    "groupA": [
      {
        "id": "A-1",
        "name": "대만 공급망",
        "source": "Yahoo Finance: TSM (70%) + UMC (30%)",
        "time": "2026-07-12 06:00",
        "newItems": 56,
        "prev": 55,
        "status": "ok"
      },
      {
        "id": "A-2",
        "name": "빅테크 CapEx",
        "source": "SEC EDGAR XBRL — 4 quarterly observations from 4 c",
        "time": "2026-07-12 06:00",
        "newItems": 57,
        "prev": 56,
        "status": "ok"
      },
      {
        "id": "A-3",
        "name": "관세청 수출",
        "source": "관세청 data.go.kr Itemtrade HS 854232 (메모리) 월간 수출 (12",
        "time": "2026-09-07 06:00",
        "newItems": 57,
        "prev": 56,
        "status": "ok"
      },
      {
        "id": "A-4",
        "name": "재고/출하 지수",
        "source": "KOSIS 광공업동향 C26 재고지수 (월간→주간 forward-fill)",
        "time": "2026-09-07 06:00",
        "newItems": 57,
        "prev": 56,
        "status": "ok"
      },
      {
        "id": "A-5",
        "name": "AWS Spot 가격",
        "source": "AWS EC2 m6i.xlarge spot (us-east-1a, 최대 90일)",
        "time": "2026-09-14 06:00",
        "newItems": 14,
        "prev": 13,
        "status": "ok"
      },
      {
        "id": "A-6",
        "name": "Manifold 봉쇄확률",
        "source": "Manifold Markets 'Will China launch a full-scale i",
        "time": "2026-09-14 06:00",
        "newItems": 51,
        "prev": 50,
        "status": "ok"
      },
      {
        "id": "A-7",
        "name": "구리 선물가",
        "source": "Yahoo Finance HG=F (COMEX Copper Futures, LME 대체)",
        "time": "2026-07-12 06:00",
        "newItems": 56,
        "prev": 55,
        "status": "ok"
      }
    ],
    "groupB": [
      {
        "id": "B-1",
        "name": "Earnings Call",
        "source": "Google News 'Earnings Call sentiment' (180 entries",
        "time": "2026-09-14 06:00",
        "newItems": 25,
        "prev": 24,
        "status": "ok"
      },
      {
        "id": "B-2",
        "name": "대만 뉴스 감성",
        "source": "TechNews.tw + Digitimes + Google News RSS (1008 en",
        "time": "2026-09-14 06:00",
        "newItems": 28,
        "prev": 27,
        "status": "ok"
      },
      {
        "id": "B-3",
        "name": "Reddit/HN",
        "source": "Hacker News Algolia ('memory chip price') — Reddit",
        "time": "2026-09-14 06:00",
        "newItems": 57,
        "prev": 56,
        "status": "ok"
      },
      {
        "id": "B-4",
        "name": "지정학 리스크",
        "source": "Caldara & Iacoviello GPR Index (https://www.matteo",
        "time": "2026-09-14 06:00",
        "newItems": 57,
        "prev": 56,
        "status": "ok"
      },
      {
        "id": "B-5",
        "name": "LTA 비율",
        "source": "Google News 'LTA ratio' (91 entries, 키워드 fallback,",
        "time": "2026-09-14 06:00",
        "newItems": 24,
        "prev": 23,
        "status": "ok"
      },
      {
        "id": "B-6",
        "name": "HBM/D램 믹스",
        "source": "Google News 'HBM mix' (163 entries, LLM 7회 호출, 42주",
        "time": "2026-09-14 06:00",
        "newItems": 42,
        "prev": 41,
        "status": "ok"
      },
      {
        "id": "B-7",
        "name": "BOM 신호",
        "source": "Hacker News Algolia API (queries: 4건)",
        "time": "2026-09-14 06:00",
        "newItems": 57,
        "prev": 56,
        "status": "ok"
      }
    ]
  }
};
