// AUTO-GENERATED by backend/pipelines/build_frontend_data.py
// DO NOT EDIT MANUALLY — regenerate via: python3 pipelines/build_frontend_data.py
// 데이터 소스: backend/data/historical/* + backend/data/validation/latest.json
//             + backend/data/news/latest.json + backend/data/events/latest.json
// 생성 시각: 2026-09-26T09:50:07.060654Z
// 뉴스/이벤트: news 10건 (Gemini LLM 분류, 2026-09-26) · events 7건 (기상이변 제외)

export const SIXSENSE_DATA = {
  "meta": {
    "current": 751.14,
    "currentChange": "+5.0%",
    "unitLabel": "메모리 3사 주가지수",
    "unitDesc": "MU 50% · SK하이닉스 30% · 삼성전자 20% 주가 가중, 2025-06-16 = 100",
    "unitShort": "pt",
    "proxyNote": "실제 DRAM 계약가가 아닌 대용 지표입니다.",
    "updated": "2026-09-26 18:50 KST",
    "insight": {
      "headline": "메모리 3사 주가지수 상승세 지속",
      "summary": "메모리 3사 주가지수는 현재 751.1pt를 기록하며 지난 1주간 5.0%, 4주간 14.4% 상승했으나, 13주 기준으로는 15.0% 하락했습니다. 최근 **AI** 관련 **HBM** 수요 증가가 일반 RAM **가격 상승**을 유발하고, DDR5 노트북 메모리 가격이 급등하는 등 긍정적인 뉴스 감성이 두드러집니다. 메모리 칩이 면적당 컴퓨트 칩보다 비싸졌다는 소식과 2027년 심각한 **메모리 부족**에 직면할 것이라는 전망도 나왔습니다. 관세청 메모리 수출액은 157억 달러를 기록했습니다.",
      "tone": "pos",
      "keySignals": [
        "A-3",
        "B-6",
        "A-4"
      ],
      "model": "Gemini gemini-2.5-flash",
      "generatedAt": "2026-09-26T09:49:55"
    }
  },
  "history": [
    {
      "week": -51,
      "date": "2025-09-29",
      "value": 152.32,
      "type": "actual"
    },
    {
      "week": -50,
      "date": "2025-10-06",
      "value": 155.16,
      "type": "actual"
    },
    {
      "week": -49,
      "date": "2025-10-13",
      "value": 169.12,
      "type": "actual"
    },
    {
      "week": -48,
      "date": "2025-10-20",
      "value": 181.34,
      "type": "actual"
    },
    {
      "week": -47,
      "date": "2025-10-27",
      "value": 191.91,
      "type": "actual"
    },
    {
      "week": -46,
      "date": "2025-11-03",
      "value": 196.86,
      "type": "actual"
    },
    {
      "week": -45,
      "date": "2025-11-10",
      "value": 197.89,
      "type": "actual"
    },
    {
      "week": -44,
      "date": "2025-11-17",
      "value": 176.57,
      "type": "actual"
    },
    {
      "week": -43,
      "date": "2025-11-24",
      "value": 191.31,
      "type": "actual"
    },
    {
      "week": -42,
      "date": "2025-12-01",
      "value": 195.9,
      "type": "actual"
    },
    {
      "week": -41,
      "date": "2025-12-08",
      "value": 200.81,
      "type": "actual"
    },
    {
      "week": -40,
      "date": "2025-12-15",
      "value": 207.16,
      "type": "actual"
    },
    {
      "week": -39,
      "date": "2025-12-22",
      "value": 224.46,
      "type": "actual"
    },
    {
      "week": -38,
      "date": "2025-12-29",
      "value": 249.82,
      "type": "actual"
    },
    {
      "week": -37,
      "date": "2026-01-05",
      "value": 273.17,
      "type": "actual"
    },
    {
      "week": -36,
      "date": "2026-01-12",
      "value": 285.04,
      "type": "actual"
    },
    {
      "week": -35,
      "date": "2026-01-19",
      "value": 302.33,
      "type": "actual"
    },
    {
      "week": -34,
      "date": "2026-01-26",
      "value": 327.89,
      "type": "actual"
    },
    {
      "week": -33,
      "date": "2026-02-02",
      "value": 310.91,
      "type": "actual"
    },
    {
      "week": -32,
      "date": "2026-02-09",
      "value": 330.16,
      "type": "actual"
    },
    {
      "week": -31,
      "date": "2026-02-16",
      "value": 347.89,
      "type": "actual"
    },
    {
      "week": -30,
      "date": "2026-02-23",
      "value": 363.44,
      "type": "actual"
    },
    {
      "week": -29,
      "date": "2026-03-02",
      "value": 320.92,
      "type": "actual"
    },
    {
      "week": -28,
      "date": "2026-03-09",
      "value": 340.29,
      "type": "actual"
    },
    {
      "week": -27,
      "date": "2026-03-16",
      "value": 355.65,
      "type": "actual"
    },
    {
      "week": -26,
      "date": "2026-03-23",
      "value": 313.95,
      "type": "actual"
    },
    {
      "week": -25,
      "date": "2026-03-30",
      "value": 313.0,
      "type": "actual"
    },
    {
      "week": -24,
      "date": "2026-04-06",
      "value": 359.27,
      "type": "actual"
    },
    {
      "week": -23,
      "date": "2026-04-13",
      "value": 388.37,
      "type": "actual"
    },
    {
      "week": -22,
      "date": "2026-04-20",
      "value": 417.37,
      "type": "actual"
    },
    {
      "week": -21,
      "date": "2026-04-27",
      "value": 443.57,
      "type": "actual"
    },
    {
      "week": -20,
      "date": "2026-05-04",
      "value": 589.17,
      "type": "actual"
    },
    {
      "week": -19,
      "date": "2026-05-11",
      "value": 596.41,
      "type": "actual"
    },
    {
      "week": -18,
      "date": "2026-05-18",
      "value": 628.7,
      "type": "actual"
    },
    {
      "week": -17,
      "date": "2026-05-25",
      "value": 771.69,
      "type": "actual"
    },
    {
      "week": -16,
      "date": "2026-06-01",
      "value": 701.74,
      "type": "actual"
    },
    {
      "week": -15,
      "date": "2026-06-08",
      "value": 756.47,
      "type": "actual"
    },
    {
      "week": -14,
      "date": "2026-06-15",
      "value": 900.37,
      "type": "actual"
    },
    {
      "week": -13,
      "date": "2026-06-22",
      "value": 884.2,
      "type": "actual"
    },
    {
      "week": -12,
      "date": "2026-06-29",
      "value": 781.75,
      "type": "actual"
    },
    {
      "week": -11,
      "date": "2026-07-06",
      "value": 746.43,
      "type": "actual"
    },
    {
      "week": -10,
      "date": "2026-07-13",
      "value": 644.16,
      "type": "actual"
    },
    {
      "week": -9,
      "date": "2026-07-20",
      "value": 661.75,
      "type": "actual"
    },
    {
      "week": -8,
      "date": "2026-07-27",
      "value": 621.72,
      "type": "actual"
    },
    {
      "week": -7,
      "date": "2026-08-03",
      "value": 598.64,
      "type": "actual"
    },
    {
      "week": -6,
      "date": "2026-08-10",
      "value": 677.36,
      "type": "actual"
    },
    {
      "week": -5,
      "date": "2026-08-17",
      "value": 687.66,
      "type": "actual"
    },
    {
      "week": -4,
      "date": "2026-08-24",
      "value": 656.71,
      "type": "actual"
    },
    {
      "week": -3,
      "date": "2026-08-31",
      "value": 689.38,
      "type": "actual"
    },
    {
      "week": -2,
      "date": "2026-09-07",
      "value": 693.27,
      "type": "actual"
    },
    {
      "week": -1,
      "date": "2026-09-14",
      "value": 715.42,
      "type": "actual"
    },
    {
      "week": 0,
      "date": "2026-09-21",
      "value": 751.14,
      "type": "actual"
    }
  ],
  "trend": {
    "change1w": 5.0,
    "change4w": 14.4,
    "change13w": -15.0,
    "high52": {
      "value": 900.37,
      "date": "2026-06-15"
    },
    "low52": {
      "value": 152.32,
      "date": "2025-09-29"
    },
    "weeklyVol13w": 7.0
  },
  "validation": {
    "runAt": "2026-09-26",
    "dataWeeks": 67,
    "dataRange": [
      "2025-06-16",
      "2026-09-21"
    ],
    "target": "메모리 3사 주가지수 (MU 50% · SK하이닉스 30% · 삼성전자 20%, 2025-06-16 = 100)",
    "baseline": "단순 기준선 — 지난주 값이 그대로 유지된다고 가정",
    "passRule": "모델 평균 오차 < 기준선 평균 오차, 그리고 4주 예측의 Diebold–Mariano 검정(겹침 보정) p < 0.05",
    "method": [
      "과거 각 시점마다 그 시점까지 정답이 확정된 데이터로만 새로 학습해 1~7주 뒤를 예측",
      "날짜를 월요일로 통일, 미래 값으로 과거를 채우지 않음",
      "월간·분기 발표 통계는 발표 지연 7주 반영 (그 시점에 실제로 알 수 있던 값만)"
    ],
    "current": {
      "week": "2026-09-21",
      "value": 751.14
    },
    "variants": [
      {
        "key": "level",
        "name": "앱이 쓰던 방식 (가격 수준 예측)",
        "byHorizon": [
          {
            "h": 1,
            "n": 39,
            "modelMape": 26.36,
            "naiveMape": 7.42,
            "winRate": 12.8,
            "dirAcc": 38.5
          },
          {
            "h": 2,
            "n": 37,
            "modelMape": 29.69,
            "naiveMape": 11.34,
            "winRate": 16.2,
            "dirAcc": 37.8
          },
          {
            "h": 3,
            "n": 35,
            "modelMape": 33.24,
            "naiveMape": 13.33,
            "winRate": 14.3,
            "dirAcc": 28.6
          },
          {
            "h": 4,
            "n": 33,
            "modelMape": 36.47,
            "naiveMape": 16.44,
            "winRate": 12.1,
            "dirAcc": 21.2
          },
          {
            "h": 5,
            "n": 31,
            "modelMape": 37.52,
            "naiveMape": 19.65,
            "winRate": 16.1,
            "dirAcc": 29.0
          },
          {
            "h": 6,
            "n": 29,
            "modelMape": 38.21,
            "naiveMape": 21.73,
            "winRate": 20.7,
            "dirAcc": 37.9
          },
          {
            "h": 7,
            "n": 27,
            "modelMape": 39.96,
            "naiveMape": 24.68,
            "winRate": 22.2,
            "dirAcc": 33.3
          }
        ],
        "overall": {
          "n": 231,
          "modelMape": 33.95,
          "naiveMape": 15.69,
          "winRate": 16.0,
          "dirAcc": 32.5,
          "alwaysUpDirAcc": 70.6,
          "underRate": 93.5,
          "pValue": 0.992
        },
        "procurement": {
          "n": 33,
          "horizonWeeks": 4,
          "alwaysNow": 528.03,
          "model": 577.21,
          "modelPct": 9.31,
          "perfectPct": -4.9,
          "waitRate": 100.0,
          "waitCount": 33,
          "waitCorrect": 7
        },
        "pass": false,
        "forecast": [
          {
            "h": 1,
            "week": "2026-09-28",
            "value": 728.76,
            "changePct": -2.98
          },
          {
            "h": 2,
            "week": "2026-10-05",
            "value": 727.98,
            "changePct": -3.08
          },
          {
            "h": 3,
            "week": "2026-10-12",
            "value": 735.4,
            "changePct": -2.09
          },
          {
            "h": 4,
            "week": "2026-10-19",
            "value": 728.35,
            "changePct": -3.03
          },
          {
            "h": 5,
            "week": "2026-10-26",
            "value": 712.85,
            "changePct": -5.1
          },
          {
            "h": 6,
            "week": "2026-11-02",
            "value": 716.86,
            "changePct": -4.56
          },
          {
            "h": 7,
            "week": "2026-11-09",
            "value": 689.47,
            "changePct": -8.21
          }
        ]
      },
      {
        "key": "return",
        "name": "개선 시도 (변화율 예측)",
        "byHorizon": [
          {
            "h": 1,
            "n": 39,
            "modelMape": 7.1,
            "naiveMape": 7.42,
            "winRate": 64.1,
            "dirAcc": 69.2
          },
          {
            "h": 2,
            "n": 37,
            "modelMape": 10.89,
            "naiveMape": 11.34,
            "winRate": 54.1,
            "dirAcc": 67.6
          },
          {
            "h": 3,
            "n": 35,
            "modelMape": 13.81,
            "naiveMape": 13.33,
            "winRate": 57.1,
            "dirAcc": 68.6
          },
          {
            "h": 4,
            "n": 33,
            "modelMape": 20.23,
            "naiveMape": 16.44,
            "winRate": 48.5,
            "dirAcc": 78.8
          },
          {
            "h": 5,
            "n": 31,
            "modelMape": 30.56,
            "naiveMape": 19.65,
            "winRate": 51.6,
            "dirAcc": 71.0
          },
          {
            "h": 6,
            "n": 29,
            "modelMape": 38.56,
            "naiveMape": 21.73,
            "winRate": 51.7,
            "dirAcc": 65.5
          },
          {
            "h": 7,
            "n": 27,
            "modelMape": 42.19,
            "naiveMape": 24.68,
            "winRate": 51.9,
            "dirAcc": 70.4
          }
        ],
        "overall": {
          "n": 231,
          "modelMape": 21.8,
          "naiveMape": 15.69,
          "winRate": 54.5,
          "dirAcc": 70.1,
          "alwaysUpDirAcc": 70.6,
          "underRate": 45.0,
          "pValue": 0.736
        },
        "procurement": {
          "n": 33,
          "horizonWeeks": 4,
          "alwaysNow": 528.03,
          "model": 528.03,
          "modelPct": 0.0,
          "perfectPct": -4.9,
          "waitRate": 0.0,
          "waitCount": 0,
          "waitCorrect": 0
        },
        "pass": false,
        "forecast": [
          {
            "h": 1,
            "week": "2026-09-28",
            "value": 794.5,
            "changePct": 5.77
          },
          {
            "h": 2,
            "week": "2026-10-05",
            "value": 831.8,
            "changePct": 10.74
          },
          {
            "h": 3,
            "week": "2026-10-12",
            "value": 869.77,
            "changePct": 15.79
          },
          {
            "h": 4,
            "week": "2026-10-19",
            "value": 829.06,
            "changePct": 10.37
          },
          {
            "h": 5,
            "week": "2026-10-26",
            "value": 815.74,
            "changePct": 8.6
          },
          {
            "h": 6,
            "week": "2026-11-02",
            "value": 838.25,
            "changePct": 11.6
          },
          {
            "h": 7,
            "week": "2026-11-09",
            "value": 774.9,
            "changePct": 3.16
          }
        ]
      }
    ],
    "pass": false,
    "verdict": "불합격",
    "explanation": {
      "status": "ok",
      "text": "이 AI 모델은 불합격 판정을 받았습니다. 합격 기준은 모델의 평균 오차가 기준선 평균 오차보다 낮고, 4주 예측의 p값이 0.05 미만이어야 하는데, 두 방식 모두 이 기준을 충족하지 못했습니다. 특히 '앱이 쓰던 방식 (가격 수준 예측)'은 예측이 실제보다 낮았던 비율이 93.5%로 매우 높았고, 오르내림 적중률 32.5%는 '항상 오른다고 찍는' 적중률 70.6%보다 훨씬 낮아 시장 방향을 제대로 예측하지 못했습니다. '개선 시도 (변화율 예측)' 방식도 오르내림 적중률 70.1%가 '항상 오른다고 찍는' 적중률 70.6%와 큰 차이가 없어 방향 예측에 강점을 보이지 못했습니다. 또한, 모델은 67주치의 데이터로 학습되었고, 예측 대상이 실제 DRAM 가격이 아닌 주가지수 대용 지표라는 한계가 있습니다. 현재 4주 뒤 예측도 '앱이 쓰던 방식'은 3.0% 하락을, '개선 시도' 방식은 10.4% 상승을 예상하여 서로 다릅니다.",
      "model": "Gemini gemini-2.5-flash",
      "reason": null,
      "attempts": 1
    }
  },
  "signalsA": [
    {
      "id": "A-1",
      "name": "대만 파운드리 주가",
      "source": "Yahoo Finance: TSM",
      "value": "+13.0%",
      "num": 0.1303,
      "tone": "pos",
      "desc": "TSMC 70%·UMC 30% 주가 (각각 2025-06-16=100 정규화, Yahoo Finance)",
      "spark": [
        0.054,
        0.168,
        0.0,
        0.149,
        0.377,
        0.633,
        0.87,
        1.0
      ],
      "recent": [
        {
          "week": "2026-03-30",
          "value": 145.0747
        },
        {
          "week": "2026-04-06",
          "value": 159.5435
        },
        {
          "week": "2026-04-13",
          "value": 166.5517
        },
        {
          "week": "2026-04-20",
          "value": 179.5038
        },
        {
          "week": "2026-04-27",
          "value": 180.7273
        },
        {
          "week": "2026-05-04",
          "value": 194.1002
        },
        {
          "week": "2026-05-11",
          "value": 198.1793
        },
        {
          "week": "2026-05-18",
          "value": 201.9769
        },
        {
          "week": "2026-05-25",
          "value": 221.1543
        },
        {
          "week": "2026-06-01",
          "value": 210.9631
        },
        {
          "week": "2026-06-08",
          "value": 220.9681
        },
        {
          "week": "2026-06-15",
          "value": 242.7132
        },
        {
          "week": "2026-06-22",
          "value": 238.2679
        },
        {
          "week": "2026-06-29",
          "value": 235.0585
        },
        {
          "week": "2026-07-06",
          "value": 234.3083
        },
        {
          "week": "2026-07-13",
          "value": 211.0346
        },
        {
          "week": "2026-07-20",
          "value": 206.227
        },
        {
          "week": "2026-07-27",
          "value": 204.8573
        },
        {
          "week": "2026-08-03",
          "value": 208.9961
        },
        {
          "week": "2026-08-10",
          "value": 212.6813
        },
        {
          "week": "2026-08-17",
          "value": 207.2382
        },
        {
          "week": "2026-08-24",
          "value": 212.0783
        },
        {
          "week": "2026-08-31",
          "value": 219.478
        },
        {
          "week": "2026-09-07",
          "value": 227.7829
        },
        {
          "week": "2026-09-14",
          "value": 235.4856
        },
        {
          "week": "2026-09-21",
          "value": 239.7111
        }
      ],
      "asOf": "2026-09-21",
      "collectedAt": "2026-09-26",
      "dataSince": "2026-09-21",
      "stale": false,
      "staleReason": null
    },
    {
      "id": "A-3",
      "name": "관세청 메모리 수출",
      "source": "관세청 data.go.kr Itemtrade HS 854232",
      "value": "15.73B",
      "num": 15733149397.0,
      "tone": "neu",
      "desc": "HS 854232 월간 수출액 USD (관세청 Open API)",
      "spark": [
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5
      ],
      "recent": [
        {
          "week": "2026-03-30",
          "value": 8012443877.0
        },
        {
          "week": "2026-04-06",
          "value": 9248046034.0
        },
        {
          "week": "2026-04-13",
          "value": 9248046034.0
        },
        {
          "week": "2026-04-20",
          "value": 9248046034.0
        },
        {
          "week": "2026-04-27",
          "value": 9248046034.0
        },
        {
          "week": "2026-05-04",
          "value": 11428371245.0
        },
        {
          "week": "2026-05-11",
          "value": 11428371245.0
        },
        {
          "week": "2026-05-18",
          "value": 11428371245.0
        },
        {
          "week": "2026-05-25",
          "value": 11428371245.0
        },
        {
          "week": "2026-06-01",
          "value": 11175623231.0
        },
        {
          "week": "2026-06-08",
          "value": 11175623231.0
        },
        {
          "week": "2026-06-15",
          "value": 11175623231.0
        },
        {
          "week": "2026-06-22",
          "value": 11175623231.0
        },
        {
          "week": "2026-06-29",
          "value": 11175623231.0
        },
        {
          "week": "2026-07-06",
          "value": 13551552131.0
        },
        {
          "week": "2026-07-13",
          "value": 13551552131.0
        },
        {
          "week": "2026-07-20",
          "value": 13551552131.0
        },
        {
          "week": "2026-07-27",
          "value": 13551552131.0
        },
        {
          "week": "2026-08-03",
          "value": 15733149397.0
        },
        {
          "week": "2026-08-10",
          "value": 15733149397.0
        },
        {
          "week": "2026-08-17",
          "value": 15733149397.0
        },
        {
          "week": "2026-08-24",
          "value": 15733149397.0
        },
        {
          "week": "2026-08-31",
          "value": 15733149397.0
        },
        {
          "week": "2026-09-07",
          "value": 15733149397.0
        },
        {
          "week": "2026-09-14",
          "value": 15733149397.0
        },
        {
          "week": "2026-09-21",
          "value": 15733149397.0
        }
      ],
      "asOf": "2026-09-21",
      "collectedAt": "2026-09-26",
      "dataSince": "2026-08-03",
      "stale": false,
      "staleReason": null
    },
    {
      "id": "A-4",
      "name": "반도체 재고지수",
      "source": "KOSIS 광업제조업동향조사 반도체 제조업",
      "value": "106.50",
      "num": 106.5,
      "tone": "neu",
      "desc": "KOSIS 광업제조업동향조사 · 반도체 제조업(C261) 생산자제품 재고지수(원지수, 2020=100), 월간",
      "spark": [
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5,
        0.5
      ],
      "recent": [
        {
          "week": "2026-03-30",
          "value": 84.8
        },
        {
          "week": "2026-04-06",
          "value": 96.8
        },
        {
          "week": "2026-04-13",
          "value": 96.8
        },
        {
          "week": "2026-04-20",
          "value": 96.8
        },
        {
          "week": "2026-04-27",
          "value": 96.8
        },
        {
          "week": "2026-05-04",
          "value": 95.5
        },
        {
          "week": "2026-05-11",
          "value": 95.5
        },
        {
          "week": "2026-05-18",
          "value": 95.5
        },
        {
          "week": "2026-05-25",
          "value": 95.5
        },
        {
          "week": "2026-06-01",
          "value": 88.7
        },
        {
          "week": "2026-06-08",
          "value": 88.7
        },
        {
          "week": "2026-06-15",
          "value": 88.7
        },
        {
          "week": "2026-06-22",
          "value": 88.7
        },
        {
          "week": "2026-06-29",
          "value": 88.7
        },
        {
          "week": "2026-07-06",
          "value": 106.5
        },
        {
          "week": "2026-07-13",
          "value": 106.5
        },
        {
          "week": "2026-07-20",
          "value": 106.5
        },
        {
          "week": "2026-07-27",
          "value": 106.5
        },
        {
          "week": "2026-08-03",
          "value": 106.5
        },
        {
          "week": "2026-08-10",
          "value": 106.5
        },
        {
          "week": "2026-08-17",
          "value": 106.5
        },
        {
          "week": "2026-08-24",
          "value": 106.5
        },
        {
          "week": "2026-08-31",
          "value": 106.5
        },
        {
          "week": "2026-09-07",
          "value": 106.5
        },
        {
          "week": "2026-09-14",
          "value": 106.5
        },
        {
          "week": "2026-09-21",
          "value": 106.5
        }
      ],
      "asOf": "2026-09-21",
      "collectedAt": "2026-09-26",
      "dataSince": "2026-07-06",
      "stale": false,
      "staleReason": null
    },
    {
      "id": "A-5",
      "name": "AWS 스팟 가격",
      "source": "AWS EC2 m6i.xlarge spot",
      "value": "$0.13",
      "num": 0.1303,
      "tone": "pos",
      "desc": "EC2 m6i.xlarge 스팟 시간당 USD (최근 90일)",
      "spark": [
        0.0,
        0.208,
        0.134,
        0.17,
        0.473,
        0.801,
        1.0,
        0.866
      ],
      "recent": [
        {
          "week": "2026-06-22",
          "value": 0.1039
        },
        {
          "week": "2026-06-29",
          "value": 0.1141
        },
        {
          "week": "2026-07-06",
          "value": 0.1336
        },
        {
          "week": "2026-07-13",
          "value": 0.1293
        },
        {
          "week": "2026-07-20",
          "value": 0.1209
        },
        {
          "week": "2026-07-27",
          "value": 0.1181
        },
        {
          "week": "2026-08-03",
          "value": 0.1128
        },
        {
          "week": "2026-08-10",
          "value": 0.117
        },
        {
          "week": "2026-08-17",
          "value": 0.1155
        },
        {
          "week": "2026-08-24",
          "value": 0.1162
        },
        {
          "week": "2026-08-31",
          "value": 0.1223
        },
        {
          "week": "2026-09-07",
          "value": 0.1289
        },
        {
          "week": "2026-09-14",
          "value": 0.133
        },
        {
          "week": "2026-09-21",
          "value": 0.1303
        }
      ],
      "asOf": "2026-09-21",
      "collectedAt": "2026-09-26",
      "dataSince": "2026-09-21",
      "stale": false,
      "staleReason": null
    },
    {
      "id": "A-6",
      "name": "대만 침공 예측시장",
      "source": "Manifold Markets 'Will China launch a fu",
      "value": "32%",
      "num": 0.3188,
      "tone": "neu",
      "desc": "Manifold Markets '2030년 전 중국의 대만 침공' 확률",
      "spark": [
        0.962,
        1.0,
        0.966,
        0.66,
        0.0,
        0.085,
        0.889,
        0.896
      ],
      "recent": [
        {
          "week": "2026-03-02",
          "value": 0.3158
        },
        {
          "week": "2026-03-09",
          "value": 0.3157
        },
        {
          "week": "2026-03-16",
          "value": 0.3303
        },
        {
          "week": "2026-03-23",
          "value": 0.3293
        },
        {
          "week": "2026-03-30",
          "value": 0.3368
        },
        {
          "week": "2026-04-06",
          "value": 0.3308
        },
        {
          "week": "2026-04-13",
          "value": 0.3482
        },
        {
          "week": "2026-04-20",
          "value": 0.3418
        },
        {
          "week": "2026-05-04",
          "value": 0.3221
        },
        {
          "week": "2026-05-11",
          "value": 0.3172
        },
        {
          "week": "2026-05-18",
          "value": 0.3242
        },
        {
          "week": "2026-05-25",
          "value": 0.3294
        },
        {
          "week": "2026-06-01",
          "value": 0.3254
        },
        {
          "week": "2026-06-15",
          "value": 0.3241
        },
        {
          "week": "2026-06-29",
          "value": 0.3309
        },
        {
          "week": "2026-07-06",
          "value": 0.3334
        },
        {
          "week": "2026-07-13",
          "value": 0.3327
        },
        {
          "week": "2026-07-20",
          "value": 0.3319
        },
        {
          "week": "2026-07-27",
          "value": 0.3219
        },
        {
          "week": "2026-08-03",
          "value": 0.3237
        },
        {
          "week": "2026-08-10",
          "value": 0.3221
        },
        {
          "week": "2026-08-17",
          "value": 0.3077
        },
        {
          "week": "2026-08-31",
          "value": 0.2767
        },
        {
          "week": "2026-09-07",
          "value": 0.2807
        },
        {
          "week": "2026-09-14",
          "value": 0.3185
        },
        {
          "week": "2026-09-21",
          "value": 0.3188
        }
      ],
      "asOf": "2026-09-21",
      "collectedAt": "2026-09-26",
      "dataSince": "2026-09-21",
      "stale": false,
      "staleReason": null
    },
    {
      "id": "A-7",
      "name": "구리 선물가",
      "source": "Yahoo Finance HG=F",
      "value": "$6.77",
      "num": 6.766,
      "tone": "pos",
      "desc": "COMEX 구리 선물 HG=F (Yahoo Finance)",
      "spark": [
        0.341,
        0.438,
        0.371,
        0.312,
        0.43,
        0.0,
        0.491,
        1.0
      ],
      "recent": [
        {
          "week": "2026-03-30",
          "value": 5.563
        },
        {
          "week": "2026-04-06",
          "value": 5.8705
        },
        {
          "week": "2026-04-13",
          "value": 6.1035
        },
        {
          "week": "2026-04-20",
          "value": 6.0235
        },
        {
          "week": "2026-04-27",
          "value": 5.932
        },
        {
          "week": "2026-05-04",
          "value": 6.249
        },
        {
          "week": "2026-05-11",
          "value": 6.2515
        },
        {
          "week": "2026-05-18",
          "value": 6.342
        },
        {
          "week": "2026-05-25",
          "value": 6.3595
        },
        {
          "week": "2026-06-01",
          "value": 6.2635
        },
        {
          "week": "2026-06-08",
          "value": 6.4305
        },
        {
          "week": "2026-06-15",
          "value": 6.354
        },
        {
          "week": "2026-06-22",
          "value": 6.1415
        },
        {
          "week": "2026-06-29",
          "value": 6.1715
        },
        {
          "week": "2026-07-06",
          "value": 6.2335
        },
        {
          "week": "2026-07-13",
          "value": 6.22
        },
        {
          "week": "2026-07-20",
          "value": 6.32
        },
        {
          "week": "2026-07-27",
          "value": 6.436
        },
        {
          "week": "2026-08-03",
          "value": 6.5705
        },
        {
          "week": "2026-08-10",
          "value": 6.5995
        },
        {
          "week": "2026-08-17",
          "value": 6.5795
        },
        {
          "week": "2026-08-24",
          "value": 6.562
        },
        {
          "week": "2026-08-31",
          "value": 6.597
        },
        {
          "week": "2026-09-07",
          "value": 6.4695
        },
        {
          "week": "2026-09-14",
          "value": 6.615
        },
        {
          "week": "2026-09-21",
          "value": 6.766
        }
      ],
      "asOf": "2026-09-21",
      "collectedAt": "2026-09-26",
      "dataSince": "2026-09-21",
      "stale": false,
      "staleReason": null
    }
  ],
  "signalsB": [
    {
      "id": "B-1",
      "name": "실적발표 뉴스 감성",
      "source": "Google News 'Earnings Call sentiment'",
      "value": "+0.20",
      "num": 0.2,
      "tone": "neu",
      "desc": "구글 뉴스 헤드라인을 Gemini 로 감성 점수화 (-1~+1)",
      "spark": [
        0.714,
        1.0,
        0.0,
        1.0,
        0.714,
        0.714,
        1.0,
        0.5
      ],
      "recent": [
        {
          "week": "2026-03-16",
          "value": 0.9
        },
        {
          "week": "2026-03-30",
          "value": 0.9
        },
        {
          "week": "2026-04-06",
          "value": 0.9
        },
        {
          "week": "2026-04-27",
          "value": 0.8
        },
        {
          "week": "2026-05-25",
          "value": 0.9
        },
        {
          "week": "2026-06-08",
          "value": 0.0
        },
        {
          "week": "2026-06-15",
          "value": 0.2
        },
        {
          "week": "2026-06-22",
          "value": 0.9
        },
        {
          "week": "2026-06-29",
          "value": 0.8
        },
        {
          "week": "2026-07-06",
          "value": -0.2
        },
        {
          "week": "2026-07-13",
          "value": -0.5
        },
        {
          "week": "2026-07-20",
          "value": 0.2
        },
        {
          "week": "2026-07-27",
          "value": 0.5
        },
        {
          "week": "2026-08-03",
          "value": 0.9
        },
        {
          "week": "2026-08-10",
          "value": -0.5
        },
        {
          "week": "2026-08-24",
          "value": 0.9
        },
        {
          "week": "2026-08-31",
          "value": 0.5
        },
        {
          "week": "2026-09-07",
          "value": 0.5
        },
        {
          "week": "2026-09-14",
          "value": 0.9
        },
        {
          "week": "2026-09-21",
          "value": 0.2
        }
      ],
      "asOf": "2026-09-21",
      "collectedAt": "2026-09-26",
      "dataSince": "2026-09-21",
      "stale": false,
      "staleReason": null
    },
    {
      "id": "B-5",
      "name": "LTA 뉴스 감성",
      "source": "Google News 'LTA ratio'",
      "value": "+0.80",
      "num": 0.8,
      "tone": "pos",
      "desc": "구글 뉴스 'LTA' 헤드라인 Gemini 감성 점수 (-1~+1)",
      "spark": [
        0.929,
        0.0,
        1.0,
        0.929,
        0.929,
        0.929,
        0.929,
        0.929
      ],
      "recent": [
        {
          "week": "2025-12-08",
          "value": 0.8
        },
        {
          "week": "2026-01-05",
          "value": 0.8
        },
        {
          "week": "2026-03-09",
          "value": 0.8
        },
        {
          "week": "2026-03-16",
          "value": 0.0
        },
        {
          "week": "2026-03-30",
          "value": 0.8
        },
        {
          "week": "2026-04-06",
          "value": 0.8
        },
        {
          "week": "2026-05-04",
          "value": 0.8
        },
        {
          "week": "2026-05-11",
          "value": 0.0
        },
        {
          "week": "2026-05-18",
          "value": 0.9
        },
        {
          "week": "2026-05-25",
          "value": 0.8
        },
        {
          "week": "2026-06-01",
          "value": 0.0
        },
        {
          "week": "2026-06-08",
          "value": 0.8
        },
        {
          "week": "2026-06-22",
          "value": 0.8
        },
        {
          "week": "2026-06-29",
          "value": 0.8
        },
        {
          "week": "2026-07-20",
          "value": -0.5
        },
        {
          "week": "2026-07-27",
          "value": 0.9
        },
        {
          "week": "2026-08-03",
          "value": 0.8
        },
        {
          "week": "2026-08-10",
          "value": 0.8
        },
        {
          "week": "2026-08-17",
          "value": 0.8
        },
        {
          "week": "2026-08-31",
          "value": 0.8
        },
        {
          "week": "2026-09-21",
          "value": 0.8
        }
      ],
      "asOf": "2026-09-21",
      "collectedAt": "2026-09-26",
      "dataSince": "2026-08-03",
      "stale": false,
      "staleReason": null
    },
    {
      "id": "B-6",
      "name": "HBM 뉴스 감성",
      "source": "Google News 'HBM mix'",
      "value": "+0.80",
      "num": 0.8,
      "tone": "pos",
      "desc": "구글 뉴스 'HBM' 헤드라인 Gemini 감성 점수 (-1~+1)",
      "spark": [
        0.0,
        0.0,
        0.0,
        0.556,
        0.889,
        0.889,
        1.0,
        0.889
      ],
      "recent": [
        {
          "week": "2026-03-02",
          "value": -0.8
        },
        {
          "week": "2026-03-09",
          "value": 0.0
        },
        {
          "week": "2026-03-16",
          "value": 0.9
        },
        {
          "week": "2026-03-30",
          "value": -0.5
        },
        {
          "week": "2026-04-06",
          "value": 0.8
        },
        {
          "week": "2026-04-13",
          "value": 0.8
        },
        {
          "week": "2026-04-20",
          "value": 1.0
        },
        {
          "week": "2026-05-04",
          "value": 0.0
        },
        {
          "week": "2026-05-11",
          "value": 0.0
        },
        {
          "week": "2026-05-18",
          "value": 1.0
        },
        {
          "week": "2026-05-25",
          "value": 1.0
        },
        {
          "week": "2026-06-01",
          "value": 0.8
        },
        {
          "week": "2026-06-08",
          "value": 0.0
        },
        {
          "week": "2026-06-29",
          "value": 0.0
        },
        {
          "week": "2026-07-06",
          "value": -0.5
        },
        {
          "week": "2026-07-13",
          "value": 0.5
        },
        {
          "week": "2026-07-20",
          "value": 0.9
        },
        {
          "week": "2026-07-27",
          "value": 0.8
        },
        {
          "week": "2026-08-03",
          "value": 0.0
        },
        {
          "week": "2026-08-10",
          "value": 0.0
        },
        {
          "week": "2026-08-17",
          "value": 0.0
        },
        {
          "week": "2026-08-24",
          "value": 0.5
        },
        {
          "week": "2026-08-31",
          "value": 0.8
        },
        {
          "week": "2026-09-07",
          "value": 0.8
        },
        {
          "week": "2026-09-14",
          "value": 0.9
        },
        {
          "week": "2026-09-21",
          "value": 0.8
        }
      ],
      "asOf": "2026-09-21",
      "collectedAt": "2026-09-26",
      "dataSince": "2026-09-21",
      "stale": false,
      "staleReason": null
    },
    {
      "id": "B-7",
      "name": "HN 메모리 화제도",
      "source": "Hacker News Algolia API",
      "value": "142.00",
      "num": 142.0,
      "tone": "neu",
      "desc": "Hacker News 메모리 관련 4개 검색어 게시글 점수",
      "spark": [
        0.009,
        0.0,
        1.0,
        0.255,
        0.03,
        0.012,
        0.435,
        0.432
      ],
      "recent": [
        {
          "week": "2026-03-23",
          "value": 4.0
        },
        {
          "week": "2026-03-30",
          "value": 55.0
        },
        {
          "week": "2026-04-06",
          "value": 256.0
        },
        {
          "week": "2026-04-13",
          "value": 2.0
        },
        {
          "week": "2026-04-20",
          "value": 0.0
        },
        {
          "week": "2026-04-27",
          "value": 134.0
        },
        {
          "week": "2026-05-04",
          "value": 0.0
        },
        {
          "week": "2026-05-11",
          "value": 13.0
        },
        {
          "week": "2026-05-18",
          "value": 690.0
        },
        {
          "week": "2026-05-25",
          "value": 26.0
        },
        {
          "week": "2026-06-01",
          "value": 53.0
        },
        {
          "week": "2026-06-08",
          "value": 6.0
        },
        {
          "week": "2026-06-15",
          "value": 2.0
        },
        {
          "week": "2026-06-22",
          "value": 54.0
        },
        {
          "week": "2026-06-29",
          "value": 23.0
        },
        {
          "week": "2026-07-06",
          "value": 12.0
        },
        {
          "week": "2026-07-13",
          "value": 0.0
        },
        {
          "week": "2026-07-20",
          "value": 30.0
        },
        {
          "week": "2026-07-27",
          "value": 3.0
        },
        {
          "week": "2026-08-03",
          "value": 0.0
        },
        {
          "week": "2026-08-10",
          "value": 329.0
        },
        {
          "week": "2026-08-17",
          "value": 84.0
        },
        {
          "week": "2026-08-24",
          "value": 10.0
        },
        {
          "week": "2026-08-31",
          "value": 4.0
        },
        {
          "week": "2026-09-07",
          "value": 143.0
        },
        {
          "week": "2026-09-14",
          "value": 142.0
        }
      ],
      "asOf": "2026-09-14",
      "collectedAt": "2026-09-26",
      "dataSince": "2026-09-14",
      "stale": false,
      "staleReason": null
    }
  ],
  "news": [
    {
      "date": "2026-09-25",
      "title": "DDR5 노트북 메모리 가격 1년 새 6배 급등",
      "titleEn": "DDR5 laptop memory prices surge 6X in 12 months — Schenker raises laptop prices and warns shortage will last through 2027, other components also on the rise - Tom's Hardware",
      "source": "RSS",
      "score": 0.9,
      "tone": "pos",
      "conf": 95,
      "hot": true,
      "summary": "DDR5 노트북 메모리 가격이 12개월 만에 6배 급등했으며, 쉥커는 노트북 가격을 인상하고 2027년까지 부족 현상이 지속될 것이라고 경고했다. 다른 부품 가격도 상승 중이다.",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "단기 분석"
        },
        "mid": {
          "tone": "pos",
          "text": "중기 분석"
        },
        "long": {
          "tone": "pos",
          "text": "장기 분석"
        }
      },
      "linked": [
        "A-4 관련",
        "B-6 관련"
      ],
      "link": "https://news.google.com/rss/articles/CBMigAJBVV95cUxOQ3JuZEFtUk5QeDZ0X2x6M0xEd01QYUpoeVgwaVVxcTZIaHlMWEJkR1Vkb05vbS1OMmtGNFlNNldORFp2aFdGdDlZdzc0YnExM3J0RXQ3Z1FvWXp3Y24zNHVhTDByamtrMy0ybmdxNzdTclI4bm9NcnBaQU9DV2l4R3R5cGNiTXBOOXNZczQ3VU4xQmJYU0w1R0ktYVUxMDhDVk9wVUx5MkJ0Mk1UX0hCRGw1bHBLMXY0aE9kVWdYZ3RpcVNza3pZS25OLUZVem5LZWlydTFvdkhnMndJSktBOXIxYWQ1b0ZEUmpnUWtHbWk0cFFQeGlKSnV1Ym50Wl9f?oc=5"
    },
    {
      "date": "2026-09-22",
      "title": "메모리 칩, 면적당 컴퓨트 칩보다 비싸져",
      "titleEn": "Memory chips are now more expensive than compute chips on a per-area basis — AI demand drives DRAM die value past leading-edge silicon - Tom's Hardware",
      "source": "RSS",
      "score": 0.9,
      "tone": "pos",
      "conf": 95,
      "hot": true,
      "summary": "AI 수요가 DRAM 다이 가치를 최첨단 실리콘보다 높게 끌어올리면서, 메모리 칩이 면적당 컴퓨트 칩보다 더 비싸졌다. 이는 AI 시대의 메모리 중요성을 강조한다.",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "단기 분석"
        },
        "mid": {
          "tone": "pos",
          "text": "중기 분석"
        },
        "long": {
          "tone": "pos",
          "text": "장기 분석"
        }
      },
      "linked": [
        "A-2 관련",
        "B-6 관련"
      ],
      "link": "https://news.google.com/rss/articles/CBMigAJBVV95cUxNc3FyNEY1Y2Z5RlVDUlE3MkdETi1ielNrTEFCeHFQc2sweUw0MWF0VTB1Q1NSVXdzMlBITWJPekMzRWxhX25acmlZQ21qVHNZSFhYdXJsVEpkOXV0enFDaHp3Z2pHSmxoVnZoUzhPVHRmUkY5bzkzV01KdFhRUlRKN1Iya0kxMVdVcnpmVVBRVlp1S1lnUE94N2E4OGVZWldMSk8zeW9DbnN5T2paejRrLTRRbkp2dWFRYkYtelAtc00wSnBMa01vSVpqaGhoSTB5UDA4SGs5RlRob09UNzZJeTlfeFNQVWFPdnpZNTEyWUNVYTJiWUVLbDdJcnUxSmlx?oc=5"
    },
    {
      "date": "2026-09-25",
      "title": "AI의 HBM 수요, 일반 RAM 가격 상승 유발",
      "titleEn": "AI's HBM Hunger Is Making Ordinary RAM More Expensive Than TSMC's Most Advanced Chips",
      "source": "Gagadget.com",
      "score": 0.9,
      "tone": "pos",
      "conf": 95,
      "hot": true,
      "summary": "AI의 HBM에 대한 높은 수요가 일반 RAM 가격을 TSMC의 최첨단 칩보다 더 비싸게 만들고 있다. 이는 AI가 메모리 시장 전반에 미치는 강력한 영향을 보여준다.",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "단기 분석"
        },
        "mid": {
          "tone": "pos",
          "text": "중기 분석"
        },
        "long": {
          "tone": "pos",
          "text": "장기 분석"
        }
      },
      "linked": [
        "B-6 관련"
      ],
      "link": "https://news.google.com/rss/articles/CBMitgFBVV95cUxOaHVLdi1hVm5pT2FTRV9KajRMU2lIcXhUNFItNmFIczR4QW8wYU01MGFmazVydHNPNU4td2xxRHVOb3FNOEZKdnpJdnlIc1M1S1RpTHB5SHJabUhBRXcyQk5QT1piYU1xSmxGeVRDVHViMjd6V2VQTy1ndzhoQzNTVHNwOV9sdlk1SXNsWUJkYlRfT2ZkbnFxX0txV3otcndrOWQxb0xZaWtOTFJjMWZnVktlRVZmUdIBuwFBVV95cUxPd0xaZ1FXWlg3Q0pjdmtfQ2NRZFFEZEZoZFFZdzVaMTJsM0Z4UGxlQzZxVmpZdXgyY1NtbW9jUFhaQ2RmWDd3Y2pBVDdoeXlIQ2dUVm9laWhZakZreEdzRjlMa3g1NE9yV0ozWFVDUXpKeURLN3AyTU1zUV9uYWJHYVAxbko4MjN2RTN1RFdoQmk4b01WdWdkUl9oMS1IRHhGT2tKNDBhRHdKamlHUlRLZTZBUE10YlFmaFpB?oc=5"
    },
    {
      "date": "2026-09-16",
      "title": "AI발 메모리 부족, 기기 설계 방식 변화",
      "titleEn": "AI-induced memory shortage is changing how devices are built, Fairphone says memory now 60% of materials cost — smaller laptop and phone makers are redesigning products and have to test for fake chips - Tom's Hardware",
      "source": "RSS",
      "score": 0.85,
      "tone": "pos",
      "conf": 90,
      "hot": true,
      "summary": "AI로 인한 메모리 부족이 기기 설계 방식을 바꾸고 있으며, 페어폰은 메모리가 재료비의 60%를 차지한다고 밝혔다. 소규모 노트북 및 휴대폰 제조업체들은 제품을 재설계하고 위조 칩 테스트를 해야 한다.",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "단기 분석"
        },
        "mid": {
          "tone": "pos",
          "text": "중기 분석"
        },
        "long": {
          "tone": "pos",
          "text": "장기 분석"
        }
      },
      "linked": [
        "A-2 관련",
        "B-6 관련"
      ],
      "link": "https://news.google.com/rss/articles/CBMi6wJBVV95cUxOS1dYNmpYUTBQd3djYlRQTEpzOXNxaWNSOElGbGd5NmptTklaUkNlNTMwR0xXa01FQWdwQ0tsVFZYR0NVcmdobkJJcW5RaG05QldZRU0yN0U4enJZOW5JSU1Mc3U2M3liOF9OdWpaQzlOUklCX1hxZG1iQV8xM0p6V3JWS1JTMmIzb1E4ZnVlV1ZITkJIUGx3U3VabWR1b3pXUXFfYVVEVTdrUGo5S3J2RzJ4aFhuVElsa25wcndnVlduQ1ZZWWw5WUg0RThvQTRaSHFqY0R1UEQtNHlnMThnLU56UWZhem43RDZUTzB0b3FPZ2N1Y2JkNlNqakFaUk9mN1l1R0VvQTdabnh0TEN4UXVJVVp0OXR6SllMMXNiT1JGTmczQjFzRjdBVTZDaFpYSjlNYUUxRUdveGxDd2RFZXk0aVRQRWhxNlpZenRlRkhaS2lwTDROd2lVYnJ4Wk1VYWF3dXhzUlB2RTA?oc=5"
    },
    {
      "date": "2026-09-10",
      "title": "메모리 칩 시장, 2027년 심각한 부족 직면",
      "titleEn": "'The memory chip market is heading toward a severe shortage': analyst firm believes RAM crisis could get far worse in 2027 — and you can blame AI ramping up",
      "source": "TechRadar",
      "score": 0.85,
      "tone": "pos",
      "conf": 90,
      "hot": true,
      "summary": "한 분석 기관은 메모리 칩 시장이 심각한 부족 사태로 향하고 있으며, 2027년에는 상황이 더욱 악화될 수 있다고 경고했다. 이는 AI 수요 증가에 기인한다.",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "단기 분석"
        },
        "mid": {
          "tone": "pos",
          "text": "중기 분석"
        },
        "long": {
          "tone": "pos",
          "text": "장기 분석"
        }
      },
      "linked": [
        "A-4 관련",
        "B-6 관련"
      ],
      "link": "https://news.google.com/rss/articles/CBMinwJBVV95cUxNaXR3TlhtMHllWjJkNXEzOTJ0U1lpSGFxX2MxVE04dUlRdVA0MG90bS1HVkJObFpBS2xISHk3YUxHV291ODVyMGRTQlUwaVNPcmxqNDZ6RDhnUENCS2szRDhPcWZBYl9Db3R6UEVTaXVmc0kyNHJNT215OGNhLUhGQVhRVGcwZFlNY3NFZXFuN2tIdjI1NW1WX2ZDTVRsZEZLZElIb2tfMC1VYWxOazlES1drQmoyWVZCblcwTU5OcDVQejM3cDFzSm5uMlJnaTdkZExBeHlzdXdab01pUGZmQk1hTHlZSlVMc2lwY0d0aDkxcHBTdlcxWUpFeXc1VHRRNVFhUzVCSC1mMWV0ZzVlbHlmRFpXVlpKRWJFWC0wOA?oc=5"
    },
    {
      "date": "2026-09-21",
      "title": "AI 메모리 부족 심화에 삼성·SK하이닉스 주가 급등",
      "titleEn": "Samsung and SK Hynix Stocks Surge as AI Memory Shortage Deepens",
      "source": "Startup Fortune",
      "score": 0.8,
      "tone": "pos",
      "conf": 90,
      "hot": true,
      "summary": "AI 메모리 부족 현상이 심화되면서 삼성과 SK하이닉스 주가가 급등했다. 이는 AI 수요가 메모리 시장에 긍정적인 영향을 미치고 있음을 보여준다.",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "단기 분석"
        },
        "mid": {
          "tone": "pos",
          "text": "중기 분석"
        },
        "long": {
          "tone": "pos",
          "text": "장기 분석"
        }
      },
      "linked": [
        "B-6 관련"
      ],
      "link": "https://news.google.com/rss/articles/CBMilgFBVV95cUxOa3o2bTFqaWRsM1lMRm44YlBFMy1FTjl3Y1Z1azFWSkNmeXU1ZUZRZ2txcFIxNlBCTHJzNEx0bDY3djBhSXd4VzZaX1RPcG5kaHp0X3FRUG9mYWdSNzNUcHdOUGd1ZXpCTmtBb1F4VXNlc0lMTGdIcFZJa0l5Ykx4UEJ3TVI0ZWdKbnFVOUw0aG5GMUxiWmc?oc=5"
    },
    {
      "date": "2026-09-24",
      "title": "마이크론 랠리, 메모리 부족 반영 전 과도",
      "titleEn": "Micron’s Rally Looks Overdone Until You Price The Memory Shortage",
      "source": "Trefis",
      "score": 0.75,
      "tone": "pos",
      "conf": 85,
      "hot": true,
      "summary": "마이크론의 주가 랠리가 메모리 부족 현상을 가격에 반영하기 전까지는 과도해 보인다는 분석이다. 이는 메모리 시장의 강세가 지속될 가능성을 시사한다.",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "단기 분석"
        },
        "mid": {
          "tone": "pos",
          "text": "중기 분석"
        },
        "long": {
          "tone": "pos",
          "text": "장기 분석"
        }
      },
      "linked": [
        "A-4 관련",
        "B-6 관련"
      ],
      "link": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxON19DYmdtVm9HcUJGcUZDZ3lmNmtSZno2UGJHbUZjRkNNd3d2Y3REM201MVN0dGI3dGxlY1RveXNxLVVYR056UjRoTWszTmw3NFpycTZYbFVEQl96Vi14TDhSWm9FaWhrdW5MTmhJYi1feVRtcHA5bzd0QlpVeWVtcnpGQXBHNjJGc1VSRGVUaHF0X2NEcGFOdGZjSkMzbFY5S1YwdXJJY0xreUE4eHFlTVA4eGFoS1VEaEp2bXNGTW0?oc=5"
    },
    {
      "date": "2026-09-17",
      "title": "AI 서버 주식 랠리, 하드웨어 수요 확대",
      "titleEn": "AI server stocks rally as hardware demand broad...",
      "source": "pluang.com",
      "score": 0.7,
      "tone": "pos",
      "conf": 80,
      "hot": true,
      "summary": "AI 서버 주식이 랠리를 보이며 하드웨어 수요가 광범위하게 확대되고 있다. 이는 AI 인프라 구축에 필요한 DRAM 등 메모리 반도체 수요 증가로 이어진다.",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "단기 분석"
        },
        "mid": {
          "tone": "pos",
          "text": "중기 분석"
        },
        "long": {
          "tone": "pos",
          "text": "장기 분석"
        }
      },
      "linked": [
        "A-2 관련"
      ],
      "link": "https://news.google.com/rss/articles/CBMisAFBVV95cUxOTWlyYWxYRnBseWE4RjJLZWhKOXVlbl9RNUo4RFlnV0hMWTJGWFJFclhrU1BZeWM4UW5kTWVicDdIdXVPMFJWaXJ1TzNTTmdMa2JKbU5XSWNUYWdSekFSYWliZTZVckk2aF9kR1MxUlBhb0JCbnB5Smp6blNuTFlFVjZLY3VGRmZzaHJqekx1eEJRM3lETERTeldQb21fU2RDLWx0aUJZR2lVMm1BdEIzTQ?oc=5"
    },
    {
      "date": "2026-09-21",
      "title": "에이서 CEO, 메모리 부족 과장 주장",
      "titleEn": "Acer CEO says memory makers are hyping 2030 shortage fears to protect margins — PC prices set to decline by late 2027, cheaper Chinese capacity coming online delivers lower memory prices - Tom's Hardware",
      "source": "RSS",
      "score": -0.7,
      "tone": "neg",
      "conf": 80,
      "hot": true,
      "summary": "에이서 CEO는 메모리 제조업체들이 마진 보호를 위해 2030년 부족 우려를 과장하고 있다고 말했다. 2027년 말까지 PC 가격이 하락하고, 저렴한 중국 생산 능력으로 메모리 가격이 낮아질 것이라고 전망했다.",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기 분석"
        },
        "mid": {
          "tone": "neg",
          "text": "중기 분석"
        },
        "long": {
          "tone": "neg",
          "text": "장기 분석"
        }
      },
      "linked": [
        "A-4 관련",
        "A-1 관련"
      ],
      "link": "https://news.google.com/rss/articles/CBMi0AJBVV95cUxPbVZDTTFRWmRmbGhzMjBtd1NBQTlkZUZWZWtXUHpUcmJUcnFrLUo3OXA0cnl6Sk9aaC1FMUJpbVNPazUzWmk4NlVRMmtmVG5YTFhjYXZMdWlvaHpodWJLYUxHQTdzamdVQmNoNGU5ZEg1X3NadlFwQWlZM1FTb3BmTXFFNGNwaGt6ZEtjVDBqeEtwTHpLYUFDWkk5d2lLb3lNOGFSYnpUXzY4UHkzUE80cUJpVTlSTE41aC14OGZYbk1YVDVfcjl5dlE5UUNwNTZyQXFHMEpwUXJfc19kTWp1bWZOWjc3amdXQk1DbWd6cm1hN2hLUUZfNTJLazVuSllBLWhTOU41STdEZVVISzRzandyNFJ4QjZfRlMwVnJkV2FVNWtFY2VZZlRZYjMzdWVvSHFtcko5OVMxWlhfamw5ZVNaR2FHeFZxRXhJS28tcHk?oc=5"
    },
    {
      "date": "2026-09-21",
      "title": "HP, 메모리 가격 급등으로 PC 출하량 감소 경고",
      "titleEn": "HP Warns PC Shipments Will Shrink Through 2027 as Memory Prices Surge",
      "source": "Startup Fortune",
      "score": -0.6,
      "tone": "neg",
      "conf": 85,
      "hot": true,
      "summary": "HP는 메모리 가격 급등으로 인해 2027년까지 PC 출하량이 감소할 것이라고 경고했다. 이는 높은 메모리 가격이 최종 제품 수요에 부정적인 영향을 미칠 수 있음을 시사한다.",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기 분석"
        },
        "mid": {
          "tone": "neg",
          "text": "중기 분석"
        },
        "long": {
          "tone": "neg",
          "text": "장기 분석"
        }
      },
      "linked": [
        "A-4 관련"
      ],
      "link": "https://news.google.com/rss/articles/CBMingFBVV95cUxNa3FWeTdCZ0dCa0ZYV2ZDTG11N0VJTHFWS2NVczNGaFlsQmN4b1hjeXpkWlk0SXB4Y2g5eUNXbWU0ZmZTbVd2ZG5iaW5zLV9kd1NLTlZxanFrUTNYbmdZT0RNU0FFR3lwUVpzTG5XRVVpZFI1eXhrdkNibWlkSDkwWjB3WkJDZno4X1gyaElwQ0s3Z1hILXpETDNJTXNWQQ?oc=5"
    }
  ],
  "macro": [
    {
      "id": "ust10",
      "asOf": "2026-09-21",
      "source": "FRED CSV DGS10",
      "unit": "%",
      "recent": [
        {
          "week": "2026-03-30",
          "value": 4.328
        },
        {
          "week": "2026-04-06",
          "value": 4.312
        },
        {
          "week": "2026-04-13",
          "value": 4.286
        },
        {
          "week": "2026-04-20",
          "value": 4.302
        },
        {
          "week": "2026-04-27",
          "value": 4.384
        },
        {
          "week": "2026-05-04",
          "value": 4.406
        },
        {
          "week": "2026-05-11",
          "value": 4.48
        },
        {
          "week": "2026-05-18",
          "value": 4.596
        },
        {
          "week": "2026-05-25",
          "value": 4.47
        },
        {
          "week": "2026-06-01",
          "value": 4.488
        },
        {
          "week": "2026-06-08",
          "value": 4.514
        },
        {
          "week": "2026-06-15",
          "value": 4.4625
        },
        {
          "week": "2026-06-22",
          "value": 4.44
        },
        {
          "week": "2026-06-29",
          "value": 4.4475
        },
        {
          "week": "2026-07-06",
          "value": 4.538
        },
        {
          "week": "2026-07-13",
          "value": 4.574
        },
        {
          "week": "2026-07-20",
          "value": 4.66
        },
        {
          "week": "2026-07-27",
          "value": 4.672
        },
        {
          "week": "2026-08-03",
          "value": 4.66
        },
        {
          "week": "2026-08-10",
          "value": 4.682
        },
        {
          "week": "2026-08-17",
          "value": 4.702
        },
        {
          "week": "2026-08-24",
          "value": 4.68
        },
        {
          "week": "2026-08-31",
          "value": 4.776
        },
        {
          "week": "2026-09-07",
          "value": 4.885
        },
        {
          "week": "2026-09-14",
          "value": 4.986
        },
        {
          "week": "2026-09-21",
          "value": 5.0525
        }
      ],
      "stale": false,
      "staleReason": null,
      "dataSince": "2026-09-21",
      "name": "미국 10년물 국채금리",
      "value": "5.05%",
      "change": "↑ 부정",
      "tone": "neg",
      "desc": "FRED DGS10 (10-Year Treasury Yield, 위험자산 선호도 지표)",
      "history": [
        4.68,
        4.7,
        4.68,
        4.78,
        4.88,
        4.99,
        5.05
      ]
    },
    {
      "id": "fed",
      "asOf": "2026-09-21",
      "source": "FRED CSV DFF",
      "unit": "%",
      "recent": [
        {
          "week": "2026-03-30",
          "value": 3.64
        },
        {
          "week": "2026-04-06",
          "value": 3.64
        },
        {
          "week": "2026-04-13",
          "value": 3.64
        },
        {
          "week": "2026-04-20",
          "value": 3.64
        },
        {
          "week": "2026-04-27",
          "value": 3.64
        },
        {
          "week": "2026-05-04",
          "value": 3.6343
        },
        {
          "week": "2026-05-11",
          "value": 3.63
        },
        {
          "week": "2026-05-18",
          "value": 3.6214
        },
        {
          "week": "2026-05-25",
          "value": 3.62
        },
        {
          "week": "2026-06-01",
          "value": 3.62
        },
        {
          "week": "2026-06-08",
          "value": 3.62
        },
        {
          "week": "2026-06-15",
          "value": 3.63
        },
        {
          "week": "2026-06-22",
          "value": 3.63
        },
        {
          "week": "2026-06-29",
          "value": 3.63
        },
        {
          "week": "2026-07-06",
          "value": 3.6229
        },
        {
          "week": "2026-07-13",
          "value": 3.6286
        },
        {
          "week": "2026-07-20",
          "value": 3.63
        },
        {
          "week": "2026-07-27",
          "value": 3.63
        },
        {
          "week": "2026-08-03",
          "value": 3.63
        },
        {
          "week": "2026-08-10",
          "value": 3.63
        },
        {
          "week": "2026-08-17",
          "value": 3.63
        },
        {
          "week": "2026-08-24",
          "value": 3.63
        },
        {
          "week": "2026-08-31",
          "value": 3.63
        },
        {
          "week": "2026-09-07",
          "value": 3.63
        },
        {
          "week": "2026-09-14",
          "value": 3.7729
        },
        {
          "week": "2026-09-21",
          "value": 3.88
        }
      ],
      "stale": false,
      "staleReason": null,
      "dataSince": "2026-09-21",
      "name": "미국 금리",
      "value": "3.88%",
      "change": "↑ 긍정",
      "tone": "neu",
      "desc": "Effective Federal Funds Rate (FRED DFF)",
      "history": [
        3.63,
        3.63,
        3.63,
        3.63,
        3.63,
        3.77,
        3.88
      ]
    },
    {
      "id": "dxy",
      "asOf": "2026-09-21",
      "source": "Yahoo Finance DX-Y.NYB",
      "unit": "",
      "recent": [
        {
          "week": "2026-03-30",
          "value": 100.03
        },
        {
          "week": "2026-04-06",
          "value": 98.65
        },
        {
          "week": "2026-04-13",
          "value": 98.1
        },
        {
          "week": "2026-04-20",
          "value": 98.51
        },
        {
          "week": "2026-04-27",
          "value": 98.21
        },
        {
          "week": "2026-05-04",
          "value": 97.84
        },
        {
          "week": "2026-05-11",
          "value": 99.27
        },
        {
          "week": "2026-05-18",
          "value": 99.32
        },
        {
          "week": "2026-05-25",
          "value": 98.91
        },
        {
          "week": "2026-06-01",
          "value": 100.07
        },
        {
          "week": "2026-06-08",
          "value": 99.75
        },
        {
          "week": "2026-06-15",
          "value": 100.85
        },
        {
          "week": "2026-06-22",
          "value": 101.36
        },
        {
          "week": "2026-06-29",
          "value": 100.86
        },
        {
          "week": "2026-07-06",
          "value": 100.97
        },
        {
          "week": "2026-07-13",
          "value": 100.75
        },
        {
          "week": "2026-07-20",
          "value": 101.47
        },
        {
          "week": "2026-07-27",
          "value": 99.8
        },
        {
          "week": "2026-08-03",
          "value": 99.6
        },
        {
          "week": "2026-08-10",
          "value": 99.67
        },
        {
          "week": "2026-08-17",
          "value": 98.8
        },
        {
          "week": "2026-08-24",
          "value": 99.7
        },
        {
          "week": "2026-08-31",
          "value": 99.16
        },
        {
          "week": "2026-09-07",
          "value": 99.12
        },
        {
          "week": "2026-09-14",
          "value": 100.22
        },
        {
          "week": "2026-09-21",
          "value": 101.035
        }
      ],
      "stale": false,
      "staleReason": null,
      "dataSince": "2026-09-21",
      "name": "달러 인덱스 (DXY)",
      "value": "101.0",
      "change": "↑ 부정",
      "tone": "neg",
      "desc": "강달러 = DRAM 수출 부정 (DX-Y.NYB)",
      "history": [
        99.67,
        98.8,
        99.7,
        99.16,
        99.12,
        100.22,
        101.03
      ]
    },
    {
      "id": "pmi",
      "asOf": "2026-09-21",
      "source": "FRED CSV INDPRO",
      "unit": "",
      "recent": [
        {
          "week": "2026-03-30",
          "value": 101.7336
        },
        {
          "week": "2026-04-06",
          "value": 102.5783
        },
        {
          "week": "2026-04-13",
          "value": 102.5783
        },
        {
          "week": "2026-04-20",
          "value": 102.5783
        },
        {
          "week": "2026-04-27",
          "value": 102.5783
        },
        {
          "week": "2026-05-04",
          "value": 102.6396
        },
        {
          "week": "2026-05-11",
          "value": 102.6396
        },
        {
          "week": "2026-05-18",
          "value": 102.6396
        },
        {
          "week": "2026-05-25",
          "value": 102.6396
        },
        {
          "week": "2026-06-01",
          "value": 102.842
        },
        {
          "week": "2026-06-08",
          "value": 102.842
        },
        {
          "week": "2026-06-15",
          "value": 102.842
        },
        {
          "week": "2026-06-22",
          "value": 102.842
        },
        {
          "week": "2026-06-29",
          "value": 102.842
        },
        {
          "week": "2026-07-06",
          "value": 103.0454
        },
        {
          "week": "2026-07-13",
          "value": 103.0454
        },
        {
          "week": "2026-07-20",
          "value": 103.0454
        },
        {
          "week": "2026-07-27",
          "value": 103.0454
        },
        {
          "week": "2026-08-03",
          "value": 103.0682
        },
        {
          "week": "2026-08-10",
          "value": 103.0682
        },
        {
          "week": "2026-08-17",
          "value": 103.0682
        },
        {
          "week": "2026-08-24",
          "value": 103.0682
        },
        {
          "week": "2026-08-31",
          "value": 103.0682
        },
        {
          "week": "2026-09-07",
          "value": 103.0682
        },
        {
          "week": "2026-09-14",
          "value": 103.0682
        },
        {
          "week": "2026-09-21",
          "value": 103.0682
        }
      ],
      "stale": false,
      "staleReason": null,
      "dataSince": "2026-08-03",
      "name": "산업생산지수",
      "value": "103.1",
      "change": "동결",
      "tone": "neu",
      "desc": "FRED INDPRO (PMI 대체)",
      "history": [
        103.07,
        103.07,
        103.07,
        103.07,
        103.07,
        103.07,
        103.07
      ]
    },
    {
      "id": "krw",
      "asOf": "2026-09-21",
      "source": "Yahoo Finance KRW=X",
      "unit": "원",
      "recent": [
        {
          "week": "2026-03-30",
          "value": 1510.26
        },
        {
          "week": "2026-04-06",
          "value": 1483.47
        },
        {
          "week": "2026-04-13",
          "value": 1466.04
        },
        {
          "week": "2026-04-20",
          "value": 1474.67
        },
        {
          "week": "2026-04-27",
          "value": 1471.73
        },
        {
          "week": "2026-05-04",
          "value": 1460.42
        },
        {
          "week": "2026-05-11",
          "value": 1496.15
        },
        {
          "week": "2026-05-18",
          "value": 1518.65
        },
        {
          "week": "2026-05-25",
          "value": 1505.96
        },
        {
          "week": "2026-06-01",
          "value": 1557.47
        },
        {
          "week": "2026-06-08",
          "value": 1516.23
        },
        {
          "week": "2026-06-15",
          "value": 1526.01
        },
        {
          "week": "2026-06-22",
          "value": 1533.12
        },
        {
          "week": "2026-06-29",
          "value": 1527.3
        },
        {
          "week": "2026-07-06",
          "value": 1497.15
        },
        {
          "week": "2026-07-13",
          "value": 1485.9301
        },
        {
          "week": "2026-07-20",
          "value": 1458.01
        },
        {
          "week": "2026-07-27",
          "value": 1441.46
        },
        {
          "week": "2026-08-03",
          "value": 1405.86
        },
        {
          "week": "2026-08-10",
          "value": 1414.97
        },
        {
          "week": "2026-08-17",
          "value": 1384.0
        },
        {
          "week": "2026-08-24",
          "value": 1375.3199
        },
        {
          "week": "2026-08-31",
          "value": 1344.61
        },
        {
          "week": "2026-09-07",
          "value": 1339.97
        },
        {
          "week": "2026-09-14",
          "value": 1384.54
        },
        {
          "week": "2026-09-21",
          "value": 1367.36
        }
      ],
      "stale": false,
      "staleReason": null,
      "dataSince": "2026-09-21",
      "name": "USD/KRW",
      "value": "1,367",
      "change": "↓ 부정",
      "tone": "pos",
      "desc": "원화 약세 = 수입 원가↑ (Yahoo KRW=X)",
      "history": [
        1414.97,
        1384.0,
        1375.32,
        1344.61,
        1339.97,
        1384.54,
        1367.36
      ]
    },
    {
      "id": "cu",
      "asOf": "2026-09-21",
      "source": "Yahoo Finance HG=F",
      "unit": "$",
      "recent": [
        {
          "week": "2026-03-30",
          "value": 5.563
        },
        {
          "week": "2026-04-06",
          "value": 5.8705
        },
        {
          "week": "2026-04-13",
          "value": 6.1035
        },
        {
          "week": "2026-04-20",
          "value": 6.0235
        },
        {
          "week": "2026-04-27",
          "value": 5.932
        },
        {
          "week": "2026-05-04",
          "value": 6.249
        },
        {
          "week": "2026-05-11",
          "value": 6.2515
        },
        {
          "week": "2026-05-18",
          "value": 6.342
        },
        {
          "week": "2026-05-25",
          "value": 6.3595
        },
        {
          "week": "2026-06-01",
          "value": 6.2635
        },
        {
          "week": "2026-06-08",
          "value": 6.4305
        },
        {
          "week": "2026-06-15",
          "value": 6.354
        },
        {
          "week": "2026-06-22",
          "value": 6.1415
        },
        {
          "week": "2026-06-29",
          "value": 6.1715
        },
        {
          "week": "2026-07-06",
          "value": 6.2335
        },
        {
          "week": "2026-07-13",
          "value": 6.22
        },
        {
          "week": "2026-07-20",
          "value": 6.32
        },
        {
          "week": "2026-07-27",
          "value": 6.436
        },
        {
          "week": "2026-08-03",
          "value": 6.5705
        },
        {
          "week": "2026-08-10",
          "value": 6.5995
        },
        {
          "week": "2026-08-17",
          "value": 6.5795
        },
        {
          "week": "2026-08-24",
          "value": 6.562
        },
        {
          "week": "2026-08-31",
          "value": 6.597
        },
        {
          "week": "2026-09-07",
          "value": 6.4695
        },
        {
          "week": "2026-09-14",
          "value": 6.615
        },
        {
          "week": "2026-09-21",
          "value": 6.766
        }
      ],
      "stale": false,
      "staleReason": null,
      "dataSince": "2026-09-21",
      "name": "구리 가격",
      "value": "$6.77",
      "change": "↑ 긍정",
      "tone": "pos",
      "desc": "LME 대체 (COMEX HG=F)",
      "history": [
        6.6,
        6.58,
        6.56,
        6.6,
        6.47,
        6.62,
        6.77
      ]
    }
  ],
  "events": [
    {
      "id": "ev-1",
      "type": "국내 반도체",
      "region": "한국",
      "risk": "low",
      "title": "SK하이닉스 파업 해결로 주가 4% 급등",
      "impact": "공급↑",
      "date": "2026-09-16",
      "summary": "SK하이닉스의 파업 위기가 해결되면서 주가가 4% 급등하며 코스피가 6,700선을 회복했다. 이는 국내 반도체 생산의 안정화에 대한 긍정적인 신호이다.",
      "effects": {
        "short": {
          "tone": "pos",
          "text": "단기적으로 파업 해결은 SK하이닉스의 생산 차질 우려를 해소하고 DRAM 공급 안정성에 긍정적 영향을 미친다."
        },
        "mid": {
          "tone": "pos",
          "text": "중기적으로는 생산 정상화로 시장에 안정적인 DRAM 공급이 가능해져 가격 변동성을 줄일 수 있다."
        },
        "long": {
          "tone": "pos",
          "text": "장기적으로는 노사 관계 안정화가 기업의 생산 효율성 및 경쟁력 강화에 기여할 수 있다."
        }
      },
      "links": [],
      "affects": [
        "A-1"
      ]
    },
    {
      "id": "ev-2",
      "type": "물리적 충돌",
      "region": "이스라엘",
      "risk": "high",
      "title": "이스라엘 대사 아들, 서안지구 테러 공격 후 뇌 수술",
      "impact": "물류↑",
      "date": "2026-09-24",
      "summary": "이스라엘 대사의 아들이 서안지구 테러 공격 후 뇌 수술을 받았다. 이는 중동 지역의 지정학적 긴장을 고조시키고, 잠재적으로 유가 및 물류에 영향을 미칠 수 있다.",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기적으로 중동 지역의 긴장 고조는 유가 상승 및 해상 운송 불안정성을 야기할 수 있다."
        },
        "mid": {
          "tone": "neg",
          "text": "중기적으로 분쟁이 확대될 경우 글로벌 공급망에 광범위한 차질을 초래하고 원자재 가격을 상승시킬 수 있다."
        },
        "long": {
          "tone": "neg",
          "text": "장기적으로는 지정학적 리스크가 지속되어 기업의 투자 심리를 위축시키고 경제 성장에 부정적 영향을 미칠 수 있다."
        }
      },
      "links": [],
      "affects": [
        "B-4",
        "A-7"
      ]
    },
    {
      "id": "ev-4",
      "type": "금융 위기",
      "region": "미국",
      "risk": "high",
      "title": "10년물 국채금리 2007년 이후 최고치",
      "impact": "수요↓",
      "date": "2026-09-23",
      "summary": "시장이 연준의 추가 금리 인상을 예상하면서 10년물 국채금리가 2007년 이후 최고 수준을 기록했다. 이는 금융 시장의 긴축 기조가 강화되고 있음을 나타낸다.",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기적으로 금리 상승은 기업의 투자 비용을 높여 반도체 수요에 부정적 영향을 줄 수 있다."
        },
        "mid": {
          "tone": "neg",
          "text": "중기적으로는 고금리 환경이 지속되어 전반적인 경제 성장 둔화와 DRAM 수요 감소를 야기할 수 있다."
        },
        "long": {
          "tone": "neg",
          "text": "장기적으로는 높은 금리가 기술 기업의 자금 조달을 어렵게 하여 혁신 및 CapEx 투자를 위축시킬 수 있다."
        }
      },
      "links": [],
      "affects": [
        "A-2"
      ]
    },
    {
      "id": "ev-5",
      "type": "기타",
      "region": "글로벌",
      "risk": "low",
      "title": "[모니터링] 글로벌 무역 정책 추적",
      "impact": "가격?",
      "date": "2026-09-24",
      "summary": "관련 헤드라인 미수집 (RSS 30일 윈도우 외) — 다음 주 수집 대기. (카테고리: 기타)",
      "effects": {
        "short": {
          "tone": "neu",
          "text": "(placeholder)"
        },
        "mid": {
          "tone": "neu",
          "text": "(placeholder)"
        },
        "long": {
          "tone": "neu",
          "text": "(placeholder)"
        }
      },
      "links": [],
      "affects": []
    },
    {
      "id": "ev-6",
      "type": "물리적 충돌",
      "region": "중동",
      "risk": "high",
      "title": "홍해 리스크 증가로 사우디 석유 수출 비용 급증",
      "impact": "물류↑",
      "date": "2026-09-24",
      "summary": "홍해 지역의 리스크가 증가하면서 사우디아라비아의 석유 수출 비용이 급증했다. 이는 중동 지역의 불안정성이 글로벌 에너지 공급망에 미치는 영향을 보여준다.",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기적으로 홍해 운송 리스크는 해상 운임 상승과 유가 불안정을 초래하여 DRAM 생산 및 운송 비용에 영향을 줄 수 있다."
        },
        "mid": {
          "tone": "neg",
          "text": "중기적으로 운송 차질이 장기화될 경우 글로벌 공급망에 병목 현상을 유발하고 원자재 수급에 어려움을 줄 수 있다."
        },
        "long": {
          "tone": "neg",
          "text": "장기적으로는 지정학적 불안정성이 지속되어 에너지 가격 상승과 인플레이션 압력을 유지하며 경제 성장을 저해할 수 있다."
        }
      },
      "links": [],
      "affects": [
        "B-4",
        "A-7"
      ]
    },
    {
      "id": "ev-8",
      "type": "금융 위기",
      "region": "미국",
      "risk": "high",
      "title": "미 10년물 국채금리 19년래 최고치 근접",
      "impact": "수요↓",
      "date": "2026-09-24",
      "summary": "미국 10년물 국채금리가 연준의 매파적 기조와 유가 100달러 상회로 인한 인플레이션 우려로 5.10% 근처까지 상승하며 19년래 최고치를 기록했다. 이는 시장의 긴축 우려를 반영한다.",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "단기적으로 높은 국채금리는 기업 자금 조달 비용을 증가시켜 투자 심리를 위축시킬 수 있다."
        },
        "mid": {
          "tone": "neg",
          "text": "중기적으로는 고금리 환경이 지속되어 전반적인 경제 활동 둔화와 DRAM 수요 감소로 이어질 수 있다."
        },
        "long": {
          "tone": "neg",
          "text": "장기적으로는 인플레이션 압력과 경기 침체 가능성이 DRAM 시장에 지속적인 하방 압력을 가할 수 있다."
        }
      },
      "links": [],
      "affects": [
        "A-7"
      ]
    },
    {
      "id": "ev-10",
      "type": "금융 위기",
      "region": "미국",
      "risk": "high",
      "title": "미-이란 회담 진전, 유가 급등, Fed 매파 기조",
      "impact": "수요↓",
      "date": "2026-09-25",
      "summary": "미-이란 회담 진전 조짐에도 유가가 급등하고 있으며, 연준 관계자들의 매파적 발언으로 10월 금리 인상 가능성이 높아졌다. 이는 글로벌 경제 불확실성을 증가시킨다.",
      "effects": {
        "short": {
          "tone": "neg",
          "text": "유가 상승과 금리 인상 가능성으로 단기적으로 시장 불안정성이 커질 수 있다."
        },
        "mid": {
          "tone": "neg",
          "text": "고유가와 고금리 기조가 지속되면 기업 투자 및 소비자 수요 위축으로 이어질 수 있다."
        },
        "long": {
          "tone": "neg",
          "text": "장기적으로는 인플레이션 압력과 경기 둔화 우려가 지속되어 DRAM 수요에 부정적 영향을 미칠 수 있다."
        }
      },
      "links": [],
      "affects": [
        "A-7"
      ]
    }
  ],
  "snapshotPast": {
    "date": "2026-07-27",
    "then": 621.72,
    "now": 751.14,
    "changePct": 20.8,
    "signals": [
      {
        "id": "A-1",
        "name": "대만 파운드리 주가",
        "then": "204.9",
        "now": "239.7",
        "direction": "up"
      },
      {
        "id": "A-2",
        "name": "빅테크 CapEx",
        "then": "165693.0",
        "now": "165693.0",
        "direction": "flat"
      },
      {
        "id": "A-3",
        "name": "관세청 메모리 수출",
        "then": "13551552131.0",
        "now": "15733149397.0",
        "direction": "up"
      },
      {
        "id": "A-4",
        "name": "반도체 재고지수",
        "then": "106.5",
        "now": "106.5",
        "direction": "flat"
      },
      {
        "id": "A-5",
        "name": "AWS 스팟 가격",
        "then": "+0.12",
        "now": "+0.13",
        "direction": "up"
      },
      {
        "id": "A-6",
        "name": "대만 침공 예측시장",
        "then": "+0.33",
        "now": "+0.32",
        "direction": "down"
      },
      {
        "id": "A-7",
        "name": "구리 선물가",
        "then": "+6.44",
        "now": "+6.77",
        "direction": "up"
      },
      {
        "id": "B-1",
        "name": "실적발표 뉴스 감성",
        "then": "+0.20",
        "now": "+0.20",
        "direction": "flat"
      },
      {
        "id": "B-2",
        "name": "대만 뉴스 감성",
        "then": "+0.09",
        "now": "+0.10",
        "direction": "up"
      },
      {
        "id": "B-3",
        "name": "HN 메모리가격 화제도",
        "then": "+2.00",
        "now": "+0.00",
        "direction": "down"
      },
      {
        "id": "B-4",
        "name": "지정학 리스크",
        "then": "167.5",
        "now": "117.9",
        "direction": "down"
      },
      {
        "id": "B-5",
        "name": "LTA 뉴스 감성",
        "then": "+0.80",
        "now": "+0.80",
        "direction": "flat"
      },
      {
        "id": "B-6",
        "name": "HBM 뉴스 감성",
        "then": "+0.80",
        "now": "+0.80",
        "direction": "flat"
      },
      {
        "id": "B-7",
        "name": "HN 메모리 화제도",
        "then": "30.0",
        "now": "142.0",
        "direction": "up"
      }
    ]
  },
  "collection": {
    "summary": {
      "total": 14,
      "success": 13,
      "stale": 1,
      "fail": 0,
      "invalid": 0
    },
    "week": "2026-09-26",
    "staleDays": 14,
    "groupA": [
      {
        "id": "A-1",
        "name": "대만 파운드리 주가",
        "source": "Yahoo Finance: TSM (70%) + UMC (30%), 각각 2025-06-1",
        "time": "2026-09-26",
        "weeks": 67,
        "dataSince": "2026-09-21",
        "reason": null,
        "status": "ok"
      },
      {
        "id": "A-2",
        "name": "빅테크 CapEx",
        "source": "SEC EDGAR XBRL — 4 quarterly observations from 4 c",
        "time": "2026-07-12",
        "weeks": 57,
        "dataSince": "2026-04-05",
        "reason": "2026-07-12 이후 수집되지 않음",
        "status": "stale"
      },
      {
        "id": "A-3",
        "name": "관세청 메모리 수출",
        "source": "관세청 data.go.kr Itemtrade HS 854232 (메모리) 월간 수출 (15",
        "time": "2026-09-26",
        "weeks": 67,
        "dataSince": "2026-08-03",
        "reason": null,
        "status": "ok"
      },
      {
        "id": "A-4",
        "name": "반도체 재고지수",
        "source": "KOSIS 광업제조업동향조사 반도체 제조업(C261) 생산자제품 재고지수(원지수, 2020",
        "time": "2026-09-26",
        "weeks": 67,
        "dataSince": "2026-07-06",
        "reason": null,
        "status": "ok"
      },
      {
        "id": "A-5",
        "name": "AWS 스팟 가격",
        "source": "AWS EC2 m6i.xlarge spot (us-east-1a, 최대 90일)",
        "time": "2026-09-26",
        "weeks": 14,
        "dataSince": "2026-09-21",
        "reason": null,
        "status": "ok"
      },
      {
        "id": "A-6",
        "name": "대만 침공 예측시장",
        "source": "Manifold Markets 'Will China launch a full-scale i",
        "time": "2026-09-26",
        "weeks": 52,
        "dataSince": "2026-09-21",
        "reason": null,
        "status": "ok"
      },
      {
        "id": "A-7",
        "name": "구리 선물가",
        "source": "Yahoo Finance HG=F (COMEX Copper Futures, LME 대체)",
        "time": "2026-09-26",
        "weeks": 67,
        "dataSince": "2026-09-21",
        "reason": null,
        "status": "ok"
      }
    ],
    "groupB": [
      {
        "id": "B-1",
        "name": "실적발표 뉴스 감성",
        "source": "Google News 'Earnings Call sentiment' (180 entries",
        "time": "2026-09-26",
        "weeks": 20,
        "dataSince": "2026-09-21",
        "reason": null,
        "status": "ok"
      },
      {
        "id": "B-2",
        "name": "대만 뉴스 감성",
        "source": "TechNews.tw + Digitimes + Google News RSS (1039 en",
        "time": "2026-09-26",
        "weeks": 26,
        "dataSince": "2026-09-21",
        "reason": null,
        "status": "ok"
      },
      {
        "id": "B-3",
        "name": "HN 메모리가격 화제도",
        "source": "Hacker News Algolia ('memory chip price') — Reddit",
        "time": "2026-09-26",
        "weeks": 56,
        "dataSince": "2026-08-10",
        "reason": null,
        "status": "ok"
      },
      {
        "id": "B-4",
        "name": "지정학 리스크",
        "source": "Caldara & Iacoviello GPR Index (https://www.matteo",
        "time": "2026-09-26",
        "weeks": 67,
        "dataSince": "2026-08-03",
        "reason": null,
        "status": "ok"
      },
      {
        "id": "B-5",
        "name": "LTA 뉴스 감성",
        "source": "Google News 'LTA ratio' (86 entries, LLM 1회 호출, 실패",
        "time": "2026-09-26",
        "weeks": 21,
        "dataSince": "2026-08-03",
        "reason": null,
        "status": "ok"
      },
      {
        "id": "B-6",
        "name": "HBM 뉴스 감성",
        "source": "Google News 'HBM mix' (162 entries, LLM 1회 호출, 실패 ",
        "time": "2026-09-26",
        "weeks": 43,
        "dataSince": "2026-09-21",
        "reason": null,
        "status": "ok"
      },
      {
        "id": "B-7",
        "name": "HN 메모리 화제도",
        "source": "Hacker News Algolia API (queries: 4건)",
        "time": "2026-09-26",
        "weeks": 56,
        "dataSince": "2026-09-14",
        "reason": null,
        "status": "ok"
      }
    ]
  }
};
